In [1]:
import pandas as pd
import random
import matplotlib.pyplot as plt
import numpy as np
import seaborn as sns
import re
from glob import glob
from pprint import pprint

## Чтение данных

Файлы с исходными данными

In [2]:
#file_amo = 'df_amocrm_sample_export_2019_01_01_2024-02-20.csv'

In [3]:
file_amo = glob('df_amocrm_sample_export_*.csv')[0]

In [4]:
file_values = 'df_list_of_values_2023_12_13.csv'

In [5]:
file_sample = 'df_certificates_list_sample.csv'

In [6]:
file_archive = 'df_codes_archieve_2024_02_20.xlsx'

In [7]:
file_amo

'df_amocrm_sample_export_2019_01_01_2024-02-26.csv'

In [8]:
date_int = re.search(r'_\d+[_-]\d+[_-]\d+[_-]\d+[_-]\d+[_-]\d+',file_amo).group(0)

In [9]:
date_int

'_2019_01_01_2024-02-26'

In [10]:
df_amo= pd.read_csv(file_amo, encoding='utf-8')

In [11]:
df_values= pd.read_csv(file_values, encoding='utf-8')

In [12]:
df_sample= pd.read_csv(file_sample , encoding='utf-8')

In [13]:
df_archive= pd.read_excel(file_archive)

In [14]:
#Вывод таблицы во всю ширину
pd.set_option('display.max_columns', None)
df_amo.head(5)

,ID,Этап сделки,Бюджет,Дата создания сделки,Дата закрытия,DELIVERY_PRICE,Стоимость доставки,PRODUCTS,PRICE,SUBTOTAL,Выручка от клиента,Направление (вид сертификата),Номер сертификата,КОРНЕВАЯ СДЕЛКА,Номер 2-го сертификата,Номер 3-го сертификата,Номер 4-го сертификата,Номер 5-го сертификата,Сертификат на тренера,Статус погашения,Дата получения услуги,Стоимость закупки
0,26975611,Успешно реализовано,4500,26.02.2024 12:36:08,26.02.2024 12:52:00,0.0,NaN,Заезд на Дрифт Трайке (Варианты: Заезд 30 мину...,4500.0,4500.0,4500,Мото Дрифт-трайк,VDT30 101669122,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4050
1,26972451,Успешно реализовано,6000,26.02.2024 10:00:59,26.02.2024 10:35:00,NaN,NaN,"Бигфуты (Варианты: 40 мин. для 1 с пассажиром,...",6000.0,6000.0,6000,Квадроциклы Бигфуты,VBF40 901660887,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4500
2,26963357,Успешно реализовано,4300,25.02.2024 11:56:47,26.02.2024 11:09:00,700.0,NaN,"Скалодром (Варианты: Start Up для двоих, Бумаж...",4300.0,3600.0,4300,Скалодром,GC2 900263473,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3000
3,26960863,Успешно реализовано,5500,25.02.2024 00:26:07,25.02.2024 09:08:00,0.0,NaN,"Снегоходы (Варианты: 1 снежик на 1 час, Бумажн...",5500.0,5500.0,5500,Снегоходы,VSN1X 101635025,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4000
4,26960249,Успешно реализовано,10000,24.02.2024 21:50:08,24.02.2024 22:04:00,0.0,NaN,Искусственная волна Flow Moscow (Варианты: 1 ч...,10000.0,10000.0,10000,Искусственная волна,VCW2 601640748,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8000

## Предобработка архивных префиксов

In [15]:
df_archive.head()

  Префикс
0   2SU24
1   2SU60
2   2WP24
3      MT
4     MTT

In [16]:
df_archive['Префикс'] = df_archive['Префикс'].str.upper()

In [17]:
df_archive = df_archive.dropna(subset=['Префикс'])

In [18]:
df_archive = df_archive.reset_index(drop=True)

In [19]:
df_archive.rename(columns = {'Префикс':'prefix'}, inplace = True )

In [20]:
df_archive.head()

  prefix
0  2SU24
1  2SU60
2  2WP24
3     MT
4    MTT

In [21]:
print(sorted(list(df_archive['prefix'].unique())))

['2SU24', '2SU60', '2WP24', 'AC2', 'AC30', 'AC60', 'AT10', 'AT15', 'AT30', 'AT4', 'AT4K', 'AT6', 'AT60', 'AT6K', 'BC1', 'BC2', 'BCR', 'BF180', 'BF40', 'BF90', 'BG', 'BGH', 'BGK', 'BGKH', 'CS20', 'CS30', 'CS40', 'CS60', 'CSR60', 'CW1', 'CW2', 'CWH', 'DRC2H', 'DT230', 'DT240', 'DT260', 'DT30', 'DT32', 'DT40', 'DT60', 'DTM', 'EB1X', 'EB1X1', 'EB2X', 'EB4X', 'ED3H', 'EDC', 'EF30', 'EF60', 'EFL30', 'EFL60', 'ES130', 'ES160', 'ES230', 'ES260', 'ESG1', 'ESG2', 'ESG4', 'F1', 'F1K', 'F2', 'FD', 'FDK', 'FJ30', 'FM30', 'FM45', 'FM60', 'FMCS30', 'FMCS45', 'FMCS45R', 'FMCS60', 'FMP15', 'FMP30', 'FMS30', 'FMS45', 'FMS60', 'FR', 'FR2', 'FROG1', 'FROG3', 'FROGM', 'GC1', 'GC2', 'GR1', 'GR1X1', 'GR2', 'GR2X1', 'GU', 'GU2', 'HB20', 'HB30', 'HY30', 'HY60', 'ICE1', 'ICE2', 'ID', 'KA2', 'KA4', 'KA6', 'KAT', 'KAT2', 'KAT4', 'KR1', 'KR2', 'KR3', 'KR4', 'KR6', 'KS', 'KS2', 'KV1X1', 'KV2X1', 'KVP1X1', 'KVP2X1', 'KVS', 'KW', 'KW2', 'KYT', 'KYT2', 'LB1X', 'LB2X', 'LB4X', 'LL1H', 'LL1HP', 'LL2H', 'LL2HP', 'LL3H', 'MB', 'MB2', 'MB2X', 'MF20', 'MF30', 'MF60', 'MT', 'MT10', 'MT10B', 'MT2', 'MT2B', 'MT5', 'MT5B', 'MTT', 'OW2', 'OWG', 'OWI', 'P1', 'P1G', 'P1P', 'P2', 'P2G', 'P2P', 'PB', 'PB2', 'PB2X', 'PH', 'PP', 'PP2', 'PPP', 'PPT', 'PR20', 'PR30', 'PR40', 'PR60', 'PS', 'RB15', 'RB20', 'RB30', 'RB40', 'RB60', 'RC', 'RCV', 'RJ', 'RJ1X', 'RJ2', 'RJ2X', 'RJXX', 'RS', 'RT', 'RTV', 'RX', 'RXV', 'S', 'S2', 'SC', 'SG10', 'SG7', 'SH', 'SH2', 'SHH', 'SK2', 'SKI20', 'SKI40', 'SKI60', 'SKT1', 'SKT10', 'SKT2', 'SKT4', 'SKT6', 'SKV', 'SN1X', 'SN1X1', 'SN2X', 'SN2X1', 'SP', 'SP2', 'ST', 'SU24', 'SU60', 'TR', 'TR1', 'TR1K', 'TR2', 'TR2K', 'TX', 'UC', 'UN', 'UNI', 'VD', 'W&F', 'WP15', 'WP2H', 'WP30', 'WP60', 'WS20', 'WS30', 'WS40', 'WS60', 'WSN40', 'WSN60', 'WTF2', 'WTF3', 'YAS', 'YEP', 'YHD']

При сортировке обнаружилась кириллица в префиксах

In [22]:
alf_ciril = 'Е Т О Р А Н К Х С В М'.split()
alf_latin = 'E T O P A H K X C B M'.split()

In [23]:
def replace_cirillic_latin(x):
    try:
        v = x
        new_v = ''
        for i in range(len(v)):
            simv = v[i]
            if simv in alf_ciril:
                pos = alf_ciril.index(simv)
                simv = alf_latin[pos]
            new_v += simv
    except:
        pass
    return new_v

In [24]:
df_archive['prefix'] = df_archive.apply(lambda x: replace_cirillic_latin(x['prefix']),axis=1)

Удаление OLD из префикса

In [25]:
df1 = df_archive[df_archive['prefix'].str.contains('OLD')]

In [26]:
df1

Empty DataFrame
Columns: [prefix]
Index: []

In [27]:
df1.shape

(0, 1)

In [28]:
#df_archive.replace(r' (OLD)|(OLD) ',r'',regex=True,inplace=True)
df_archive.replace(r'( *OLD *)',r'',regex=True,inplace=True)

In [29]:
df1.head()

Empty DataFrame
Columns: [prefix]
Index: []

In [30]:
#df_archive.iloc[246]['prefix']

In [31]:
df1.shape

(0, 1)

Удаление **+ Карта Тренер**, **+T**

In [32]:
df_archive.replace(r'( *\+ *\S* *[Т|T]\S*)',r'T',regex=True,inplace=True)

In [33]:
print(sorted(list(df_archive['prefix'].unique())))

['2SU24', '2SU60', '2WP24', 'AC2', 'AC30', 'AC60', 'AT10', 'AT15', 'AT30', 'AT4', 'AT4K', 'AT6', 'AT60', 'AT6K', 'BC1', 'BC2', 'BCR', 'BF180', 'BF40', 'BF90', 'BG', 'BGH', 'BGK', 'BGKH', 'CS20', 'CS30', 'CS40', 'CS60', 'CSR60', 'CW1', 'CW2', 'CWH', 'DRC2H', 'DT230', 'DT240', 'DT260', 'DT30', 'DT32', 'DT40', 'DT60', 'DTM', 'EB1X', 'EB1X1', 'EB2X', 'EB4X', 'ED3H', 'EDC', 'EF30', 'EF60', 'EFL30', 'EFL60', 'ES130', 'ES160', 'ES230', 'ES260', 'ESG1', 'ESG2', 'ESG4', 'F1', 'F1K', 'F2', 'FD', 'FDK', 'FJ30', 'FM30', 'FM45', 'FM60', 'FMCS30', 'FMCS45', 'FMCS45R', 'FMCS60', 'FMP15', 'FMP30', 'FMS30', 'FMS45', 'FMS60', 'FR', 'FR2', 'FROG1', 'FROG3', 'FROGM', 'GC1', 'GC2', 'GR1', 'GR1X1', 'GR2', 'GR2X1', 'GU', 'GU2', 'HB20', 'HB30', 'HY30', 'HY60', 'ICE1', 'ICE2', 'ID', 'KA2', 'KA4', 'KA6', 'KAT', 'KAT2', 'KAT4', 'KR1', 'KR2', 'KR3', 'KR4', 'KR6', 'KS', 'KS2', 'KV1X1', 'KV2X1', 'KVP1X1', 'KVP2X1', 'KVS', 'KW', 'KW2', 'KYT', 'KYT2', 'LB1X', 'LB2X', 'LB4X', 'LL1H', 'LL1HP', 'LL2H', 'LL2HP', 'LL3H', 'MB', 'MB2', 'MB2X', 'MF20', 'MF30', 'MF60', 'MT', 'MT10', 'MT10B', 'MT2', 'MT2B', 'MT5', 'MT5B', 'MTT', 'OW2', 'OWG', 'OWI', 'P1', 'P1G', 'P1P', 'P2', 'P2G', 'P2P', 'PB', 'PB2', 'PB2X', 'PH', 'PP', 'PP2', 'PPP', 'PPT', 'PR20', 'PR30', 'PR40', 'PR60', 'PS', 'RB15', 'RB20', 'RB30', 'RB40', 'RB60', 'RC', 'RCV', 'RJ', 'RJ1X', 'RJ2', 'RJ2X', 'RJXX', 'RS', 'RT', 'RTV', 'RX', 'RXV', 'S', 'S2', 'SC', 'SG10', 'SG7', 'SH', 'SH2', 'SHH', 'SK2', 'SKI20', 'SKI40', 'SKI60', 'SKT1', 'SKT10', 'SKT2', 'SKT4', 'SKT6', 'SKV', 'SN1X', 'SN1X1', 'SN2X', 'SN2X1', 'SP', 'SP2', 'ST', 'SU24', 'SU60', 'TR', 'TR1', 'TR1K', 'TR2', 'TR2K', 'TX', 'UC', 'UN', 'UNI', 'VD', 'W&F', 'WP15', 'WP2H', 'WP30', 'WP60', 'WS20', 'WS30', 'WS40', 'WS60', 'WSN40', 'WSN60', 'WTF2', 'WTF3', 'YAS', 'YEP', 'YHD']

Имеются двойные префиксы MT/MT2 и MT10/MT10B

In [34]:
archive_prefix = list(df_archive['prefix'].unique())

## Предобработка активных префиксов

In [35]:
df_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Id              198 non-null    int64
 1   Activity Name   198 non-null    object
 2   Value           196 non-null    object
 3   Status          198 non-null    object
 4   Prefix          198 non-null    object
 5   Purchase Price  167 non-null    float64
 6   Sale Price      196 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 11.0+ KB

In [36]:
df_values.columns = df_values.columns.str.lower()

In [37]:
df_values.columns = df_values.columns.str.strip()

In [38]:
df_values.columns = df_values.columns.map(lambda x: re.sub( '(?<!^)(?=[ ])', '_', x ).lower())
df_values.columns = df_values.columns.map(lambda x: re.sub( ' ', '', x ))

In [39]:
df_values.head(5)

,id,activity_name,value,status,prefix,purchase_price,sale_price
0,1,Вейксёрф и вейкборд,2 часа вейксерфинга или вейкбординга\r\nна вол...,on_air,WS2,NaN,22500.0
1,2,Вейксёрф и вейкборд,1 час вейксерфинга или вейкбординга\r\nна волн...,on_air,WS1,NaN,11000.0
2,3,Вейксёрф и вейкборд,40 минут вейксерфинга или вейкбординга\r\nна в...,on_air,WS40,NaN,7500.0
3,4,Вейксёрф и вейкборд,30 минут вейксерфинга или вейкбординга\r\nна в...,on_air,WS30,NaN,5500.0
4,5,Вейксёрф и вейкборд,25 минут вейксерфинга или вейкбординга\r\nна в...,on_air,WS25,NaN,5000.0

In [40]:
df_values.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 198 entries, 0 to 197
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id              198 non-null    int64
 1   activity_name   198 non-null    object
 2   value           196 non-null    object
 3   status          198 non-null    object
 4   prefix          198 non-null    object
 5   purchase_price  167 non-null    float64
 6   sale_price      196 non-null    float64
dtypes: float64(2), int64(1), object(4)
memory usage: 11.0+ KB

In [41]:
print(sorted(list(df_values['prefix'].unique())))

['2MWP24', '2WP24', 'AB', 'AB4', 'AB4G', 'ABG', 'AC2', 'AC30', 'AC60', 'AT10', 'AT15', 'AT30', 'AT4', 'AT4K', 'AT6', 'AT60', 'AT6K', 'BF180', 'BF40', 'BF90', 'BG', 'BGH', 'BGK', 'BGKH', 'CS20', 'CS30', 'CS40', 'CS60', 'CSR60', 'CW1', 'CW1T', 'CW2', 'CW2T', 'CWH', 'DRC2H', 'DRCH', 'DT30', 'DT32', 'DT40', 'DT42', 'DT60', 'DT62', 'DTM', 'EB1x', 'EB2x', 'EB4x', 'ED3H', 'EDС', 'EFL30', 'EFL60', 'FR', 'FR2,', 'FRK', 'FRT', 'FRTK', 'GC1', 'GC2', 'GR1', 'GR2', 'GU', 'GU2', 'HB30', 'HB60', 'HY30', 'HY60', 'KA2', 'KA4', 'KA6', 'KAT', 'KAT2', 'KAT4', 'KS', 'KS2', 'KV1X1', 'KV2X1', 'KVP1X1', 'KVP2X1', 'KW', 'KW2', 'KYT', 'KYT2', 'LL1H', 'LL1HP', 'LL2H', 'LL2HP', 'LL3H', 'MB', 'MB2', 'MB2X', 'MEFL30', 'MEFL60', 'MF20', 'MF30', 'MF60', 'MHB60', 'MHY30', 'MHY60', 'MMF20', 'MMF30', 'MMF60', 'MSKI40', 'MSKI60', 'MSU24', 'MSU60', 'MT10', 'MW&F', 'MWP15', 'MWP2H', 'MWP60', 'MWS1', 'MWS2', 'MWS25', 'MWS30', 'MWS40', 'MWSN1', 'MWSN2', 'MWSN25', 'MWSN40', 'OW2', 'OWG', 'OWI', 'PL15', 'PL20', 'PL30', 'PP', 'PP2', 'PP2P', 'PP2S', 'PPP', 'PPS', 'PPT', 'PR20', 'PR30', 'PR40', 'PR60', 'RB15', 'RB20', 'RB30', 'RB40', 'RB60', 'RC', 'RCV', 'RJ', 'RJ2', 'RT', 'RTV', 'RX', 'RXV', 'SG10', 'SG5', 'SH', 'SH2', 'SHH', 'SK', 'SK2', 'SK2V', 'SKI40', 'SKI60', 'SKT', 'SKT1', 'SKT10', 'SKT2', 'SKT4', 'SKT6', 'SKV', 'SN1X', 'SN2X', 'SU24', 'SU60', 'SUT', 'TB', 'TB2', 'TB4', 'W&F', 'WP15', 'WP2H', 'WP60', 'WS1', 'WS2', 'WS25', 'WS30', 'WS40', 'WSN1', 'WSN2', 'WSN25', 'WSN40', 'WTF2', 'WTF3', 'YAS', 'YEР', 'YHD', 'МТ', 'МТ5', 'МТТ', 'РB', 'РB2', 'РB2X']

Все prefix прописные. Имеется кириллица в префиксах

In [42]:
df_values['prefix'] = df_values['prefix'].str.upper()

In [43]:
df_values['prefix'] = df_values.apply(lambda x: replace_cirillic_latin(x['prefix']),axis=1)

In [44]:
prefix_values = list(df_values['prefix'].unique())

In [45]:
print(sorted((prefix_values)))

['2MWP24', '2WP24', 'AB', 'AB4', 'AB4G', 'ABG', 'AC2', 'AC30', 'AC60', 'AT10', 'AT15', 'AT30', 'AT4', 'AT4K', 'AT6', 'AT60', 'AT6K', 'BF180', 'BF40', 'BF90', 'BG', 'BGH', 'BGK', 'BGKH', 'CS20', 'CS30', 'CS40', 'CS60', 'CSR60', 'CW1', 'CW1T', 'CW2', 'CW2T', 'CWH', 'DRC2H', 'DRCH', 'DT30', 'DT32', 'DT40', 'DT42', 'DT60', 'DT62', 'DTM', 'EB1X', 'EB2X', 'EB4X', 'ED3H', 'EDC', 'EFL30', 'EFL60', 'FR', 'FR2,', 'FRK', 'FRT', 'FRTK', 'GC1', 'GC2', 'GR1', 'GR2', 'GU', 'GU2', 'HB30', 'HB60', 'HY30', 'HY60', 'KA2', 'KA4', 'KA6', 'KAT', 'KAT2', 'KAT4', 'KS', 'KS2', 'KV1X1', 'KV2X1', 'KVP1X1', 'KVP2X1', 'KW', 'KW2', 'KYT', 'KYT2', 'LL1H', 'LL1HP', 'LL2H', 'LL2HP', 'LL3H', 'MB', 'MB2', 'MB2X', 'MEFL30', 'MEFL60', 'MF20', 'MF30', 'MF60', 'MHB60', 'MHY30', 'MHY60', 'MMF20', 'MMF30', 'MMF60', 'MSKI40', 'MSKI60', 'MSU24', 'MSU60', 'MT', 'MT10', 'MT5', 'MTT', 'MW&F', 'MWP15', 'MWP2H', 'MWP60', 'MWS1', 'MWS2', 'MWS25', 'MWS30', 'MWS40', 'MWSN1', 'MWSN2', 'MWSN25', 'MWSN40', 'OW2', 'OWG', 'OWI', 'PB', 'PB2', 'PB2X', 'PL15', 'PL20', 'PL30', 'PP', 'PP2', 'PP2P', 'PP2S', 'PPP', 'PPS', 'PPT', 'PR20', 'PR30', 'PR40', 'PR60', 'RB15', 'RB20', 'RB30', 'RB40', 'RB60', 'RC', 'RCV', 'RJ', 'RJ2', 'RT', 'RTV', 'RX', 'RXV', 'SG10', 'SG5', 'SH', 'SH2', 'SHH', 'SK', 'SK2', 'SK2V', 'SKI40', 'SKI60', 'SKT', 'SKT1', 'SKT10', 'SKT2', 'SKT4', 'SKT6', 'SKV', 'SN1X', 'SN2X', 'SU24', 'SU60', 'SUT', 'TB', 'TB2', 'TB4', 'W&F', 'WP15', 'WP2H', 'WP60', 'WS1', 'WS2', 'WS25', 'WS30', 'WS40', 'WSN1', 'WSN2', 'WSN25', 'WSN40', 'WTF2', 'WTF3', 'YAS', 'YEP', 'YHD']

In [46]:
len(prefix_values)

197

#### Объединенный список префиксов

In [47]:
all_prefix = list(set(prefix_values).union(set(archive_prefix)))

In [48]:
all_prefix.sort()

In [49]:
print(all_prefix)

['2MWP24', '2SU24', '2SU60', '2WP24', 'AB', 'AB4', 'AB4G', 'ABG', 'AC2', 'AC30', 'AC60', 'AT10', 'AT15', 'AT30', 'AT4', 'AT4K', 'AT6', 'AT60', 'AT6K', 'BC1', 'BC2', 'BCR', 'BF180', 'BF40', 'BF90', 'BG', 'BGH', 'BGK', 'BGKH', 'CS20', 'CS30', 'CS40', 'CS60', 'CSR60', 'CW1', 'CW1T', 'CW2', 'CW2T', 'CWH', 'DRC2H', 'DRCH', 'DT230', 'DT240', 'DT260', 'DT30', 'DT32', 'DT40', 'DT42', 'DT60', 'DT62', 'DTM', 'EB1X', 'EB1X1', 'EB2X', 'EB4X', 'ED3H', 'EDC', 'EF30', 'EF60', 'EFL30', 'EFL60', 'ES130', 'ES160', 'ES230', 'ES260', 'ESG1', 'ESG2', 'ESG4', 'F1', 'F1K', 'F2', 'FD', 'FDK', 'FJ30', 'FM30', 'FM45', 'FM60', 'FMCS30', 'FMCS45', 'FMCS45R', 'FMCS60', 'FMP15', 'FMP30', 'FMS30', 'FMS45', 'FMS60', 'FR', 'FR2', 'FR2,', 'FRK', 'FROG1', 'FROG3', 'FROGM', 'FRT', 'FRTK', 'GC1', 'GC2', 'GR1', 'GR1X1', 'GR2', 'GR2X1', 'GU', 'GU2', 'HB20', 'HB30', 'HB60', 'HY30', 'HY60', 'ICE1', 'ICE2', 'ID', 'KA2', 'KA4', 'KA6', 'KAT', 'KAT2', 'KAT4', 'KR1', 'KR2', 'KR3', 'KR4', 'KR6', 'KS', 'KS2', 'KV1X1', 'KV2X1', 'KVP1X1', 'KVP2X1', 'KVS', 'KW', 'KW2', 'KYT', 'KYT2', 'LB1X', 'LB2X', 'LB4X', 'LL1H', 'LL1HP', 'LL2H', 'LL2HP', 'LL3H', 'MB', 'MB2', 'MB2X', 'MEFL30', 'MEFL60', 'MF20', 'MF30', 'MF60', 'MHB60', 'MHY30', 'MHY60', 'MMF20', 'MMF30', 'MMF60', 'MSKI40', 'MSKI60', 'MSU24', 'MSU60', 'MT', 'MT10', 'MT10B', 'MT2', 'MT2B', 'MT5', 'MT5B', 'MTT', 'MW&F', 'MWP15', 'MWP2H', 'MWP60', 'MWS1', 'MWS2', 'MWS25', 'MWS30', 'MWS40', 'MWSN1', 'MWSN2', 'MWSN25', 'MWSN40', 'OW2', 'OWG', 'OWI', 'P1', 'P1G', 'P1P', 'P2', 'P2G', 'P2P', 'PB', 'PB2', 'PB2X', 'PH', 'PL15', 'PL20', 'PL30', 'PP', 'PP2', 'PP2P', 'PP2S', 'PPP', 'PPS', 'PPT', 'PR20', 'PR30', 'PR40', 'PR60', 'PS', 'RB15', 'RB20', 'RB30', 'RB40', 'RB60', 'RC', 'RCV', 'RJ', 'RJ1X', 'RJ2', 'RJ2X', 'RJXX', 'RS', 'RT', 'RTV', 'RX', 'RXV', 'S', 'S2', 'SC', 'SG10', 'SG5', 'SG7', 'SH', 'SH2', 'SHH', 'SK', 'SK2', 'SK2V', 'SKI20', 'SKI40', 'SKI60', 'SKT', 'SKT1', 'SKT10', 'SKT2', 'SKT4', 'SKT6', 'SKV', 'SN1X', 'SN1X1', 'SN2X', 'SN2X1', 'SP', 'SP2', 'ST', 'SU24', 'SU60', 'SUT', 'TB', 'TB2', 'TB4', 'TR', 'TR1', 'TR1K', 'TR2', 'TR2K', 'TX', 'UC', 'UN', 'UNI', 'VD', 'W&F', 'WP15', 'WP2H', 'WP30', 'WP60', 'WS1', 'WS2', 'WS20', 'WS25', 'WS30', 'WS40', 'WS60', 'WSN1', 'WSN2', 'WSN25', 'WSN40', 'WSN60', 'WTF2', 'WTF3', 'YAS', 'YEP', 'YHD']

In [50]:
len(all_prefix)

292

In [51]:
archive_prefix = list(set(archive_prefix) - set(prefix_values))

In [52]:
archive_prefix.sort()

Измененный **archive_prefix**

In [53]:
print(archive_prefix)

['2SU24', '2SU60', 'BC1', 'BC2', 'BCR', 'DT230', 'DT240', 'DT260', 'EB1X1', 'EF30', 'EF60', 'ES130', 'ES160', 'ES230', 'ES260', 'ESG1', 'ESG2', 'ESG4', 'F1', 'F1K', 'F2', 'FD', 'FDK', 'FJ30', 'FM30', 'FM45', 'FM60', 'FMCS30', 'FMCS45', 'FMCS45R', 'FMCS60', 'FMP15', 'FMP30', 'FMS30', 'FMS45', 'FMS60', 'FR2', 'FROG1', 'FROG3', 'FROGM', 'GR1X1', 'GR2X1', 'HB20', 'ICE1', 'ICE2', 'ID', 'KR1', 'KR2', 'KR3', 'KR4', 'KR6', 'KVS', 'LB1X', 'LB2X', 'LB4X', 'MT10B', 'MT2', 'MT2B', 'MT5B', 'P1', 'P1G', 'P1P', 'P2', 'P2G', 'P2P', 'PH', 'PS', 'RJ1X', 'RJ2X', 'RJXX', 'RS', 'S', 'S2', 'SC', 'SG7', 'SKI20', 'SN1X1', 'SN2X1', 'SP', 'SP2', 'ST', 'TR', 'TR1', 'TR1K', 'TR2', 'TR2K', 'TX', 'UC', 'UN', 'UNI', 'VD', 'WP30', 'WS20', 'WS60', 'WSN60']

In [54]:
len(archive_prefix)

95

In [55]:
df_amo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8368 entries, 0 to 8367
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   ID                             8368 non-null   int64
 1   Этап сделки                    8368 non-null   object
 2   Бюджет                         8368 non-null   int64
 3   Дата создания сделки           8368 non-null   object
 4   Дата закрытия                  8368 non-null   object
 5   DELIVERY_PRICE                 5614 non-null   float64
 6   Стоимость доставки             504 non-null    object
 7   PRODUCTS                       7449 non-null   object
 8   PRICE                          7449 non-null   float64
 9   SUBTOTAL                       7405 non-null   float64
 10  Выручка от клиента             8162 non-null   object
 11  Направление (вид сертификата)  8246 non-null   object
 12  Номер сертификата              8368 non-null   object
 13  КОРНЕВАЯ СДЕЛКА                159 non-null    object
 14  Номер 2-го сертификата         714 non-null    object
 15  Номер 3-го сертификата         10 non-null     object
 16  Номер 4-го сертификата         4 non-null      object
 17  Номер 5-го сертификата         27 non-null     object
 18  Сертификат на тренера          112 non-null    object
 19  Статус погашения               3288 non-null   object
 20  Дата получения услуги          3259 non-null   object
 21  Стоимость закупки              2715 non-null   object
dtypes: float64(3), int64(2), object(17)
memory usage: 1.4+ MB

In [56]:
df_values.head(10)

,id,activity_name,value,status,prefix,purchase_price,sale_price
0,1,Вейксёрф и вейкборд,2 часа вейксерфинга или вейкбординга\r\nна вол...,on_air,WS2,NaN,22500.0
1,2,Вейксёрф и вейкборд,1 час вейксерфинга или вейкбординга\r\nна волн...,on_air,WS1,NaN,11000.0
2,3,Вейксёрф и вейкборд,40 минут вейксерфинга или вейкбординга\r\nна в...,on_air,WS40,NaN,7500.0
3,4,Вейксёрф и вейкборд,30 минут вейксерфинга или вейкбординга\r\nна в...,on_air,WS30,NaN,5500.0
4,5,Вейксёрф и вейкборд,25 минут вейксерфинга или вейкбординга\r\nна в...,on_air,WS25,NaN,5000.0
5,6,Вейксёрф и вейкборд,2 часа вейксерфинга или вейкбординга\r\nна люб...,on_air,WSN2,NaN,26500.0
6,7,Вейксёрф и вейкборд,1 час вейксерфинга или вейкбординга на любой в...,on_air,WSN1,NaN,13500.0
7,8,Вейксёрф и вейкборд,40 минут вейксерфинга или вейкбординга на любо...,on_air,WSN40,NaN,8500.0
8,9,Вейксёрф и вейкборд,25 минут вейксерфинга или вейкбординга на любо...,on_air,WSN25,NaN,6000.0
9,10,Флайборд,1 час полёта на флайборде,on_air,MF60,NaN,12500.0

## Предобработка базы AMO

### Имена столбцов

Столбцы в нижний регистр и удаление пробелов

In [57]:
df_amo.columns = df_amo.columns.str.lower()

In [58]:
df_amo.columns = df_amo.columns.str.strip()

In [59]:
df_amo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8368 entries, 0 to 8367
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   id                             8368 non-null   int64
 1   этап сделки                    8368 non-null   object
 2   бюджет                         8368 non-null   int64
 3   дата создания сделки           8368 non-null   object
 4   дата закрытия                  8368 non-null   object
 5   delivery_price                 5614 non-null   float64
 6   стоимость доставки             504 non-null    object
 7   products                       7449 non-null   object
 8   price                          7449 non-null   float64
 9   subtotal                       7405 non-null   float64
 10  выручка от клиента             8162 non-null   object
 11  направление (вид сертификата)  8246 non-null   object
 12  номер сертификата              8368 non-null   object
 13  корневая сделка                159 non-null    object
 14  номер 2-го сертификата         714 non-null    object
 15  номер 3-го сертификата         10 non-null     object
 16  номер 4-го сертификата         4 non-null      object
 17  номер 5-го сертификата         27 non-null     object
 18  сертификат на тренера          112 non-null    object
 19  статус погашения               3288 non-null   object
 20  дата получения услуги          3259 non-null   object
 21  стоимость закупки              2715 non-null   object
dtypes: float64(3), int64(2), object(17)
memory usage: 1.4+ MB

Удаление пробелов и вставка символа "_"

In [60]:
df_amo.columns = df_amo.columns.map(lambda x: re.sub( '(?<!^)(?=[ ])', '_', x ).lower())
df_amo.columns = df_amo.columns.map(lambda x: re.sub( ' ', '', x ))

Копирование исходной базы

In [61]:
df_amo_temp = df_amo.copy()

Переименование столбцов

In [62]:
df_amo_temp.rename(columns = {'номер_сертификата':'code', 'id':'amo_id','дата_закрытия':'sale_date','дата_получения_услуги':'card_used_date'}, inplace = True )

In [63]:
df_values.rename(columns = {'id':'activity_value_id' }, inplace = True )

In [64]:
df_amo_temp['code'] = df_amo_temp['code'].str.upper()

In [65]:
df_amo_temp['номер_2-го_сертификата'] = df_amo_temp['номер_2-го_сертификата'].str.upper()

In [66]:
df_amo_temp['номер_3-го_сертификата'] = df_amo_temp['номер_3-го_сертификата'].str.upper()

In [67]:
df_amo_temp['номер_4-го_сертификата'] = df_amo_temp['номер_4-го_сертификата'].str.upper()

In [68]:
df_amo_temp['номер_5-го_сертификата'] = df_amo_temp['номер_5-го_сертификата'].str.upper()

In [69]:
#df_amo_temp['сертификат_на_фотографа'] = df_amo_temp['сертификат_на_фотографа'].str.upper()

In [70]:
df_amo_temp['сертификат_на_тренера'] = df_amo_temp['сертификат_на_тренера'].str.upper()

In [71]:
df_amo_temp['дата_создания_сделки'] = pd.to_datetime(df_amo_temp['дата_создания_сделки'] )

C:\Users\Admin\AppData\Local\Temp\ipykernel_3008\1868446354.py:1: UserWarning: Parsing dates in %d.%m.%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_amo_temp['дата_создания_сделки'] = pd.to_datetime(df_amo_temp['дата_создания_сделки'] )

In [72]:
df_amo_temp['sale_date'] = pd.to_datetime(df_amo_temp['sale_date'])

C:\Users\Admin\AppData\Local\Temp\ipykernel_3008\3706027285.py:1: UserWarning: Parsing dates in %d.%m.%Y %H:%M:%S format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_amo_temp['sale_date'] = pd.to_datetime(df_amo_temp['sale_date'])

In [73]:
df_amo_temp['card_used_date'] = pd.to_datetime(df_amo_temp['card_used_date'],errors='coerce')

C:\Users\Admin\AppData\Local\Temp\ipykernel_3008\2138346124.py:1: UserWarning: Parsing dates in %d.%m.%Y format when dayfirst=False (the default) was specified. Pass `dayfirst=True` or specify a format to silence this warning.
  df_amo_temp['card_used_date'] = pd.to_datetime(df_amo_temp['card_used_date'],errors='coerce')

In [74]:
df_amo_temp = df_amo_temp.sort_values(by=["дата_создания_сделки"], ascending=True)

In [75]:
#df_amo_temp['supplier_payment_date'] = df_amo_temp['card_used_date']

In [76]:
df_amo_temp = df_amo_temp.reset_index(drop=True)

In [77]:
df_amo_temp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8368 entries, 0 to 8367
Data columns (total 22 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   amo_id                         8368 non-null   int64
 1   этап_сделки                    8368 non-null   object
 2   бюджет                         8368 non-null   int64
 3   дата_создания_сделки           8368 non-null   datetime64[ns]
 4   sale_date                      8368 non-null   datetime64[ns]
 5   delivery_price                 5614 non-null   float64
 6   стоимость_доставки             504 non-null    object
 7   products                       7449 non-null   object
 8   price                          7449 non-null   float64
 9   subtotal                       7405 non-null   float64
 10  выручка_от_клиента             8162 non-null   object
 11  направление_(вид_сертификата)  8246 non-null   object
 12  code                           8368 non-null   object
 13  корневая_сделка                159 non-null    object
 14  номер_2-го_сертификата         714 non-null    object
 15  номер_3-го_сертификата         10 non-null     object
 16  номер_4-го_сертификата         4 non-null      object
 17  номер_5-го_сертификата         27 non-null     object
 18  сертификат_на_тренера          112 non-null    object
 19  статус_погашения               3288 non-null   object
 20  card_used_date                 3259 non-null   datetime64[ns]
 21  стоимость_закупки              2715 non-null   object
dtypes: datetime64[ns](3), float64(3), int64(2), object(14)
memory usage: 1.4+ MB

In [78]:
df_amo_temp.head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки
0,660235,Успешно реализовано,3290,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный сертификатна Квадроциклы (Выберите ...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1 01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,667573,Успешно реализовано,2600,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный сертификатна Флайборд (Выберите тип...,2600.0,2600.0,NaN,Флайборд / Ховерборд / Ранец,MF20 95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN
2,929417,Успешно реализовано,3040,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,929931,Успешно реализовано,7200,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф и вейк за катером,VWS60 22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,938619,Успешно реализовано,6000,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный сертификатна Квадроциклы (Выберите ...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1 01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

Определение разделителей в поле **code**

In [79]:
cc = df_amo_temp['code'].unique()

In [80]:
set_cc = set()

In [81]:
for el in cc:
    set_cc.update(el)

In [82]:
print(set_cc)

{'1', '_', 'С', 'X', '4', 'W', 'R', ')', 'A', 'Н', 'Е', 'K', 'G', 'Б', '3', '6', 'О', 'Y', ' ', '0', 'V', 'U', '8', '(', '5', '\xa0', 'И', 'F', 'M', 'Р', 'Т', '?', 'H', 'S', 'I', 'А', 'В', 'C', 'Х', '9', 'У', 'P', 'J', 'T', 'B', 'L', 'К', 'E', 'D', 'М', '-', '2', 'N', '7', '&'}

В качестве разделителей используются символы ' ', '_', '\xa0' и их комбинации

## Создание отдельных строк для дополнительных сертификатов

Кол-во строк до вставки

In [83]:
df_amo_temp.shape

(8368, 22)

In [84]:
dop_sert = ['номер_2-го_сертификата',
            'номер_3-го_сертификата',
            'номер_4-го_сертификата',
            'номер_5-го_сертификата',
            'сертификат_на_тренера']

Списки amo_id для каждого дополнительного сертификата

In [85]:
dopsert_amoid = dict()

In [86]:
for el in dop_sert:
    dopsert_amoid[el] = []

In [87]:
def insert_row_for_sert(row):
    global field
    global dopsert_amoid
    df_amo_temp.loc[len(df_amo_temp.index)] = [row['amo_id'],
                                           np.NaN,
                                          np.NaN,
                                           row['дата_создания_сделки'],
                                           row['sale_date'],
                                          np.NaN,
                                          np.NaN,
                                          np.NaN,
                                          np.NaN,
                                          0,
                                          np.NaN,
                                          '',
                                          row[field],
                                          np.NaN,
                                          np.NaN,
                                          np.NaN,
                                          np.NaN,
                                          np.NaN,
                                          np.NaN,
                                          np.NaN,
                                               np.NaN,
                                               np.NaN
                                              ]
    
    dopsert_amoid[field].append(row['amo_id'])
    return 1

In [88]:
dop_sert = ['номер_2-го_сертификата',
            'номер_3-го_сертификата',
            'номер_4-го_сертификата',
            'номер_5-го_сертификата',
            'сертификат_на_тренера']

In [89]:
for field in dop_sert:
    #Выборка строк для конкретного вида сертификата
    df_dop_sert = df_amo_temp.loc[(df_amo_temp[field].notna())] 
    print(f'Обнаружено строк для {field} {df_dop_sert.shape[0]}')
    #Удаление из выборки DISABLED сертификатов
    df_dop_sert = df_dop_sert.loc[~df_dop_sert[field].str.contains('DI')]
    df_dop_sert['qq']= df_dop_sert.apply(insert_row_for_sert,axis=1)

Обнаружено строк для номер_2-го_сертификата 714
Обнаружено строк для номер_3-го_сертификата 10
Обнаружено строк для номер_4-го_сертификата 4
Обнаружено строк для номер_5-го_сертификата 27
Обнаружено строк для сертификат_на_тренера 112

Значения amo_id для добавленных строк

In [90]:
print(dopsert_amoid)

{'номер_2-го_сертификата': [1418327, 2043467, 4964131, 6215467, 6614575, 7222395, 7282273, 8080921, 8339403, 8466069, 8524755, 8554889, 8577515, 8735307, 8737067, 8752703, 8758685, 8759963, 8772277, 8825921, 8856331, 8858903, 8929915, 8959005, 8965363, 8977113, 9001603, 9048327, 9059237, 9081331, 9175871, 9342679, 9366361, 9389463, 9413677, 9492007, 9502035, 9591959, 9623353, 9754667, 9770445, 9800017, 10034469, 10056799, 10166533, 10217139, 10247573, 10312373, 10368935, 10391643, 10448925, 10503552, 10581427, 10820831, 10821667, 10987291, 11023407, 11150997, 14113625, 14182589, 14227789, 14406227, 14481653, 14618295, 14838483, 14941809, 14951341, 14966121, 14974381, 14982303, 14986817, 14989887, 14993197, 14998273, 15001421, 15038675, 15044431, 15048297, 15051807, 15089667, 15318697, 15337583, 15397881, 15402427, 15499835, 15589627, 15821679, 15942605, 15943793, 16018461, 16019883, 16057309, 16081611, 16097677, 16163011, 16174057, 16191065, 16198601, 16202345, 16205835, 16231457, 16256447, 16267543, 16277519, 16278377, 16288215, 16312455, 16375749, 16515229, 16669813, 16910343, 16948119, 16991447, 17010439, 17187007, 17218319, 17266777, 17354135, 17357121, 17375129, 17382505, 17385245, 17442951, 17443441, 17459895, 17507923, 17523887, 17715829, 17826907, 17835461, 17870559, 17913229, 17915381, 18057007, 18151225, 18229795, 18266447, 18272957, 18310403, 18384055, 18392181, 18406187, 18426105, 18433123, 18491491, 18507415, 18554909, 18565061, 18572499, 18580801, 18584081, 18611785, 18611881, 18612757, 18622899, 18627925, 18642615, 18689863, 18700607, 18704981, 18707425, 18708811, 18769077, 18788645, 18819781, 18826135, 18839207, 18844165, 18851807, 18947603, 18955955, 18957025, 18974327, 18982457, 18993431, 18993651, 19014285, 19018281, 19029671, 19071375, 19073465, 19098265, 19103469, 19112845, 19115667, 19120289, 19123367, 19125089, 19135117, 19143233, 19169689, 19171863, 19172991, 19179971, 19180235, 19192481, 19197729, 19228203, 19233107, 19233741, 19281441, 19282667, 19282775, 19290731, 19301311, 19303593, 19303993, 19307669, 19313253, 19316401, 19325355, 19330016, 19333096, 19340440, 19342120, 19346244, 19363818, 19364006, 19370085, 19378589, 19381325, 19382855, 19383709, 19390645, 19390939, 19390975, 19398091, 19398479, 19399659, 19400067, 19403849, 19411421, 19416223, 19419781, 19425781, 19432523, 19441228, 19443536, 19444268, 19455822, 19462676, 19472708, 19499082, 19503468, 19509488, 19512223, 19512731, 19520833, 19524307, 19529509, 19536237, 19545647, 19548815, 19549221, 19552983, 19554279, 19562597, 19562695, 19580631, 19606099, 19612225, 19617006, 19617470, 19640242, 19645838, 19659874, 19709002, 19744397, 19770123, 19808987, 19811151, 19865797, 19933211, 20000311, 20075285, 20180247, 20302222, 20339003, 20368957, 20382671, 20391671, 20401789, 20413715, 20418629, 20420667, 20468829, 20525211, 20569271, 20636773, 20640231, 20654103, 20678623, 20692085, 20716707, 20722561, 20722829, 20730371, 20733477, 20736421, 20760305, 20763613, 20764207, 20764983, 20782051, 20852943, 20868407, 20906317, 20918891, 20927863, 20977915, 21051299, 21077859, 21078003, 21082887, 21089551, 21091859, 21095493, 21102855, 21136693, 21142465, 21142691, 21145029, 21156987, 21157019, 21161795, 21174199, 21189187, 21198351, 21227649, 21298445, 21330403, 21354383, 21356347, 21496716, 21513087, 21530661, 21567185, 21605913, 21615687, 21634447, 21661915, 21665393, 21689087, 21697517, 21701303, 21715687, 21727621, 21738517, 21751733, 21763567, 21785889, 21803843, 21814949, 21821819, 21826963, 21836335, 21840889, 21841091, 21845017, 21848927, 21849645, 21850315, 21858919, 21867723, 21871223, 21873761, 21881231, 21885249, 21896601, 21897445, 21904583, 21904685, 21905059, 21907805, 21910417, 21912849, 21913049, 21918403, 21928011, 21891947, 21931955, 21964973, 21970599, 21976181, 21977065, 21972649, 21977577, 21985043, 21985857, 21986415, 21990207, 21991099, 21995385, 21995409, 21996393, 22000277, 22002755, 22012397, 22012801, 22013703, 22018025, 22022551, 22022911, 22027911, 22030363, 22033381, 22046243, 22050045, 22055455, 22058881, 22059755, 22059929, 22060711, 22061203, 22063501, 22070649, 22074263, 22078429, 22079429, 22108227, 22108561, 22109811, 22110883, 22110907, 22113583, 22117419, 22127117, 22127867, 22128533, 22128635, 22133043, 22133455, 22125805, 22133581, 22136017, 22139393, 22140881, 22141011, 22141071, 22141181, 22144737, 22145435, 22146019, 22146767, 22147177, 22149395, 22152797, 22155095, 22171187, 22174259, 22177971, 22179079, 22180835, 22183361, 22183683, 22187585, 22188365, 22188363, 22194759, 22200043, 22189571, 22206779, 22212901, 22213191, 22213323, 22214419, 22218313, 22218361, 22219419, 22224451, 22224785, 22225235, 22200315, 22230405, 22230893, 22231273, 22233535, 22237041, 22238851, 22240067, 22242889, 22244061, 22244187, 22244069, 22246905, 22255781, 22258131, 22258921, 22245833, 22274335, 22277095, 22285821, 22286321, 22296021, 22284953, 22301633, 22303685, 22304421, 22305137, 22311111, 22314241, 22321795, 22322569, 22323575, 22326731, 22327073, 22328981, 22329885, 22337113, 22335759, 22337569, 22348685, 22353885, 22354021, 22364381, 22368703, 22369375, 22369655, 22372093, 22372949, 22374379, 22378205, 22379273, 22379737, 22384225, 22384601, 22388537, 22394417, 22396087, 22415093, 22435575, 22435543, 22436781, 22453273, 22460377, 22464027, 22468147, 22484369, 22490361, 22495555, 22492765, 22483979, 22514953, 22550239, 22630279, 22630285, 22630307, 22630323, 22630357, 22630361, 22633937, 22637497, 22662789, 22668753, 22677505, 22679137, 22685729, 22727295, 22747811, 22770455, 22769733, 22965321, 23083243, 23139083, 23630943, 23499379, 24913421, 23653805, 23665131, 23680799, 23717211, 23719721, 23778849, 23967057, 24124551, 24207425, 24207485, 24209199, 24283109, 24308797, 24321529, 24360787, 24370199, 24407599, 24413703, 24413747, 24441731, 24460403, 24462079, 24486770, 24524175, 24525169, 24531685, 24640239, 24650609, 24656289, 24663991, 24678509, 24718623, 24752957, 24754939, 24785491, 24790463, 24855063, 24867945, 24918947, 24949815, 24989577, 25126121, 25113117, 25183973, 25538207, 25739449, 25881419, 25899441, 25938825, 26034025, 26095709, 26139623, 26171801, 26283781, 26322205, 26342225, 26347871, 26361559, 26365097, 26371193, 26386633, 26386677, 26410699, 26411041, 26430197, 26432777, 26433695, 26433703, 26433973, 26434555, 26444581, 26475549, 26498981, 26520995, 26651431, 26674399, 26707117, 26786303, 26792067, 26833325, 26835293, 26845127, 26872657, 26876489, 26906683, 26909005, 26910087, 26930585, 26940535, 26940559, 26946317, 26949433], 'номер_3-го_сертификата': [23139083, 23717211, 24124551, 24855063, 26845127, 26876489, 26906683, 26910087, 26946317, 26949433], 'номер_4-го_сертификата': [24124551, 26906683, 26910087], 'номер_5-го_сертификата': [7966017, 8080921, 8527405, 8772277, 8959005, 9129063, 9177519, 22369655, 23394167, 23967057, 24124551, 24207485, 24308797, 24324573, 24436793, 24437239, 24584857, 24611547, 24718623, 24854545, 24867945, 24901233, 24901319, 24986247, 25538207], 'сертификат_на_тренера': [7243017, 17742885, 23188225, 23246841, 23264685, 23314439, 23356503, 23502729, 23513149, 23596239, 23601589, 23623467, 23676913, 23692773, 23714709, 23719323, 23751513, 23788533, 23801865, 23810513, 23810559, 23813621, 23852821, 23869621, 23873785, 23882253, 23885027, 23897495, 23908435, 23931579, 23959347, 23967057, 24000379, 24013075, 24048603, 24056111, 24083997, 24084061, 24088395, 24092835, 24119097, 24120549, 24108655, 24048077, 24122263, 24124551, 24177210, 24184388, 24207425, 24207679, 24285861, 24295901, 24308797, 24310757, 24323277, 24343649, 24350347, 24362083, 24417659, 24463739, 24464305, 24511935, 24514453, 24521673, 24527773, 24595337, 24560639, 24599637, 24604611, 24606011, 24611905, 24614375, 24615849, 24649213, 24650609, 24665969, 24678905, 24708927, 24721963, 24734827, 24746589, 24754809, 24757207, 24819125, 24774585, 24777563, 24779567, 24807245, 24867945, 24875347, 25010135, 25010515, 25045555, 25112995, 25153497, 25153589, 25190897, 25197379, 25273975, 25418131, 25449091, 25956059, 26036943, 25821661, 26330613, 26371193, 26497325, 26549271, 26622873, 26725365, 26846311]}

В базу AMO добавлены строки для дополнительных сертификатов

Кол-во строк после вставки

In [91]:
df_amo_temp.shape

(9176, 22)

Замена кириллицы на латинские символы

In [92]:
#df_amo_temp['code'] = df_amo_temp.apply(replace_cirillic_latin,axis=1)
df_amo_temp['code'] = df_amo_temp.apply(lambda x: replace_cirillic_latin(x['code']),axis=1)

Замена всех возможных разделителей на '_'

In [93]:
#df_amo_temp['code'] = df_amo_temp['code'].str.replace('[^_ \xa0]+([ _\xa0]+)\d+','_',regex=True)
df_amo_temp.replace(r'([ _\xa0]+)',r'_',regex=True,inplace=True)

In [94]:
df_amo_temp.head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки
0,660235,Успешно_реализовано,3290.0,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный_сертификатна_Квадроциклы_(Выберите_...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1_01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
3,929931,Успешно_реализовано,7200.0,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,VWS60_22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN
4,938619,Успешно_реализовано,6000.0,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1_01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN

### Формирование новых столбцов в базе АМО

In [95]:
df_amo_temp['id'] = ''

#### prefix and number

In [96]:
df_amo_temp['prefix'] = df_amo_temp['code'].apply(lambda x: re.split('[ _]',x)[0] if ' ' in x or '_' in x else '')

In [97]:
df_amo_temp['number'] = df_amo_temp['code'].apply(lambda x: re.split('[ _]',x)[1] if ' ' in x or '_' in x else '')

In [98]:
df_amo_temp.head(10)

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number
0,660235,Успешно_реализовано,3290.0,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный_сертификатна_Квадроциклы_(Выберите_...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1_01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X1,01053659
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF20,95425
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
3,929931,Успешно_реализовано,7200.0,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,VWS60_22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VWS60,22477
4,938619,Успешно_реализовано,6000.0,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1_01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP2X1,01053332
5,948101,Успешно_реализовано,5290.0,2020-03-04 17:11:49,2020-07-10 18:34:00,NaN,NaN,Подарочный_сертификатна_Сап-Сёрфинг_(Выберите_...,5290.0,5000.0,NaN,САП-сёрф,SU24_43411,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-08-09,NaN,,SU24,43411
6,1058967,Успешно_реализовано,2750.0,2020-03-05 10:42:16,2020-03-08 05:05:00,NaN,NaN,Подарочный_сертификат_в_крытый_Вейк-парк_(Выбе...,2750.0,2750.0,NaN,NaN,GRT_232948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,GRT,232948
7,1418327,Успешно_реализовано,12000.0,2020-03-06 22:49:50,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Квадроциклы,VKV1X1_02095845,NaN,VKV1X1_020264,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VKV1X1,02095845
8,1447181,Успешно_реализовано,4000.0,2020-03-07 13:55:30,2020-07-10 18:34:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,4000.0,4000.0,NaN,Квадроциклы,KVP1X1_01053485,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X1,01053485
9,1447597,Успешно_реализовано,8000.0,2020-03-07 14:12:10,2020-07-10 18:34:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,8000.0,8000.0,NaN,Квадроциклы,KVP2X1_01041987,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP2X1,01041987

In [99]:
prefix_amo = list(df_amo_temp['prefix'].unique())
prefix_amo.sort()
prefix_amo = prefix_amo[1:]

In [100]:
prefix_amo.sort(key=lambda x: len(x),reverse=True)

In [101]:
print(prefix_amo)

['VMF306120784', 'MF30134139', 'VHY60T30', 'FMCS45R', 'VFMCS30', 'VKVP1X1', 'VKVP2X1', 'VMWSN40', 'VSKI40T', 'VSKI60T', 'VWS20TR', 'VWSN40T', 'VWSN60T', '60WAKE', 'FMCS30', 'KVP1X1', 'KVP1X2', 'KVP2X1', 'MWSN40', 'V2SU24', 'V2SU60', 'V2WP24', 'VBF180', 'VDRC2H', 'VEFL30', 'VES130', 'VES160', 'VES230', 'VGR1X1', 'VHY30T', 'VKV1X1', 'VKV2X1', 'VKVP1X', 'VMMF20', 'VMMF30', 'VMSU60', 'VMWP15', 'VMWS25', 'VMWS40', 'VSKI20', 'VSKI40', 'VSKI60', 'VSN1X1', 'VSN2X1', 'VSN2X4', 'VWS20T', 'VWS30T', 'VWS40T', 'VWS60T', 'VWSN25', 'VWSN40', 'VWSN60', '2SU60', '2WP24', 'BF180', 'DRC2H', 'DT230', 'DT240', 'DT260', 'EB1X1', 'EFL30', 'EFL60', 'ES130', 'ES160', 'ES230', 'FMP30', 'GR1X1', 'GR2X1', 'KV1X1', 'KV2X1', 'LL1HP', 'MMF60', 'MWS25', 'SKI40', 'SKI60', 'SN1X1', 'SN2X1', 'VAC30', 'VAC60', 'VAT10', 'VAT15', 'VAT30', 'VAT4K', 'VAT6K', 'VBF40', 'VBF90', 'VBGKH', 'VCS20', 'VCS30', 'VCS40', 'VCS60', 'VCW1T', 'VCW2T', 'VDRCH', 'VDT30', 'VDT32', 'VDT40', 'VDT42', 'VDT60', 'VDT62', 'VEB1X', 'VEB2X', 'VED3H', 'VEF30', 'VEF60', 'VESG1', 'VESG2', 'VFJ30', 'VFM30', 'VFM45', 'VHB20', 'VHB30', 'VHB60', 'VHY30', 'VHY60', 'VJT4A', 'VKAT2', 'VKAT4', 'VKV1X', 'VLB1X', 'VLL1H', 'VLL2H', 'VLL3H', 'VMB2X', 'VMF20', 'VMF30', 'VMF60', 'VMT10', 'VMT2B', 'VMW&F', 'VMWS1', 'VPB2X', 'VPH20', 'VPP2P', 'VPP2S', 'VPR20', 'VPR30', 'VPR40', 'VPR60', 'VRB15', 'VRB20', 'VRB30', 'VRB40', 'VRJ1X', 'VRJ2X', 'VSG10', 'VSK2V', 'VSKT1', 'VSKT2', 'VSKT4', 'VSN1X', 'VSN2X', 'VSN60', 'VSU24', 'VSU60', 'VTR1K', 'VTR2K', 'VTR30', 'VWP15', 'VWP2H', 'VWP60', 'VWS20', 'VWS25', 'VWS30', 'VWS40', 'VWS60', 'VWTF2', 'WS30T', 'WSN40', 'WSN60', 'AC30', 'AC60', 'AT10', 'AT15', 'AT30', 'AT4K', 'AT6K', 'BF40', 'BF90', 'BGKH', 'CS20', 'CS30', 'CS40', 'CS60', 'DRCH', 'DT30', 'DT40', 'DT60', 'EB1X', 'EB2X', 'ED3H', 'EF30', 'EF60', 'ESG1', 'ESG2', 'FJ30', 'FM30', 'FM45', 'FM60', 'HB20', 'HB30', 'HY30', 'HY60', 'KAT2', 'KAT4', 'LL1H', 'LL2H', 'MB2X', 'MF20', 'MF30', 'MF60', 'MT2B', 'MWS2', 'PB2X', 'PL15', 'PL20', 'PR20', 'PR30', 'PR40', 'PR60', 'RB15', 'RB20', 'RB30', 'RJ2X', 'SG10', 'SKT1', 'SKT2', 'SKT4', 'SN1X', 'SN2X', 'SU24', 'SU60', 'TR1K', 'TR2K', 'VAC2', 'VAT4', 'VAT6', 'VAWP', 'VBGH', 'VBGK', 'VCW1', 'VCW2', 'VCWH', 'VDTM', 'VEDC', 'VEFL', 'VFR2', 'VFRT', 'VGC1', 'VGC2', 'VGR1', 'VGR2', 'VGU2', 'VJT2', 'VKA2', 'VKA4', 'VKA6', 'VKAT', 'VKR1', 'VKR3', 'VKVS', 'VMB2', 'VMT2', 'VMT5', 'VMTT', 'VP1G', 'VPB2', 'VPP2', 'VPPP', 'VPPS', 'VPPT', 'VRCV', 'VRJ2', 'VRTV', 'VSG5', 'VSG7', 'VSH2', 'VSK2', 'VSKT', 'VSKV', 'VSUT', 'VSVH', 'VTB2', 'VTR1', 'VTR2', 'VW&F', 'VWPA', 'VWS1', 'VWS6', 'VWTF', 'VYAS', 'VYEP', 'WP15', 'WP24', 'WP2H', 'WP30', 'WP60', 'WS20', 'WS25', 'WS30', 'WS40', 'WS60', 'WTF2', 'WTF3', 'AT4', 'AT6', 'BGH', 'CW1', 'CW2', 'EDC', 'GC1', 'GC2', 'GR1', 'GR2', 'GRT', 'GU2', 'JT2', 'KA2', 'KA4', 'KA6', 'KAT', 'KR1', 'KR2', 'KR4', 'KS2', 'KVC', 'KVS', 'MB2', 'MT2', 'MT5', 'MTT', 'P1G', 'P1P', 'P2G', 'PB2', 'PP2', 'PPP', 'RCV', 'RJ2', 'RTV', 'RXV', 'SG7', 'SH2', 'SHH', 'SK2', 'SKV', 'SP2', 'TR1', 'TR2', 'VBG', 'VFR', 'VGU', 'VMB', 'VMT', 'VP1', 'VPB', 'VPH', 'VPP', 'VRC', 'VRJ', 'VRS', 'VS2', 'VSH', 'VSK', 'VSP', 'VST', 'VTR', 'VUN', 'VWF', 'VWS', 'W&F', 'YEP', 'AT', 'BG', 'F1', 'GU', 'KS', 'MB', 'MF', 'MT', 'P1', 'P2', 'PB', 'PH', 'PS', 'RC', 'RJ', 'RS', 'RX', 'S2', 'SH', 'SP', 'ST', 'TR', 'UN', 'VS', 'WF', 'S']

Некоторые значения в code без разделителей, потому не выделились prefix и number

Отделение prefix от number

In [102]:
all_prefix_sort = all_prefix

In [103]:
all_prefix_sort.sort(key=lambda x: len(x),reverse=True)

In [104]:
all_prefix_sort

['FMCS45R',
 '2MWP24',
 'FMCS30',
 'FMCS45',
 'FMCS60',
 'KVP1X1',
 'KVP2X1',
 'MEFL30',
 'MEFL60',
 'MSKI40',
 'MSKI60',
 'MWSN25',
 'MWSN40',
 '2SU24',
 '2SU60',
 '2WP24',
 'BF180',
 'CSR60',
 'DRC2H',
 'DT230',
 'DT240',
 'DT260',
 'EB1X1',
 'EFL30',
 'EFL60',
 'ES130',
 'ES160',
 'ES230',
 'ES260',
 'FMP15',
 'FMP30',
 'FMS30',
 'FMS45',
 'FMS60',
 'FROG1',
 'FROG3',
 'FROGM',
 'GR1X1',
 'GR2X1',
 'KV1X1',
 'KV2X1',
 'LL1HP',
 'LL2HP',
 'MHB60',
 'MHY30',
 'MHY60',
 'MMF20',
 'MMF30',
 'MMF60',
 'MSU24',
 'MSU60',
 'MT10B',
 'MWP15',
 'MWP2H',
 'MWP60',
 'MWS25',
 'MWS30',
 'MWS40',
 'MWSN1',
 'MWSN2',
 'SKI20',
 'SKI40',
 'SKI60',
 'SKT10',
 'SN1X1',
 'SN2X1',
 'WSN25',
 'WSN40',
 'WSN60',
 'AB4G',
 'AC30',
 'AC60',
 'AT10',
 'AT15',
 'AT30',
 'AT4K',
 'AT60',
 'AT6K',
 'BF40',
 'BF90',
 'BGKH',
 'CS20',
 'CS30',
 'CS40',
 'CS60',
 'CW1T',
 'CW2T',
 'DRCH',
 'DT30',
 'DT32',
 'DT40',
 'DT42',
 'DT60',
 'DT62',
 'EB1X',
 'EB2X',
 'EB4X',
 'ED3H',
 'EF30',
 'EF60',
 'ESG1',
 'ESG2',
 'ESG4',
 'FJ30',
 'FM30',
 'FM45',
 'FM60',
 'FR2,',
 'FRTK',
 'HB20',
 'HB30',
 'HB60',
 'HY30',
 'HY60',
 'ICE1',
 'ICE2',
 'KAT2',
 'KAT4',
 'KYT2',
 'LB1X',
 'LB2X',
 'LB4X',
 'LL1H',
 'LL2H',
 'LL3H',
 'MB2X',
 'MF20',
 'MF30',
 'MF60',
 'MT10',
 'MT2B',
 'MT5B',
 'MW&F',
 'MWS1',
 'MWS2',
 'PB2X',
 'PL15',
 'PL20',
 'PL30',
 'PP2P',
 'PP2S',
 'PR20',
 'PR30',
 'PR40',
 'PR60',
 'RB15',
 'RB20',
 'RB30',
 'RB40',
 'RB60',
 'RJ1X',
 'RJ2X',
 'RJXX',
 'SG10',
 'SK2V',
 'SKT1',
 'SKT2',
 'SKT4',
 'SKT6',
 'SN1X',
 'SN2X',
 'SU24',
 'SU60',
 'TR1K',
 'TR2K',
 'WP15',
 'WP2H',
 'WP30',
 'WP60',
 'WS20',
 'WS25',
 'WS30',
 'WS40',
 'WS60',
 'WSN1',
 'WSN2',
 'WTF2',
 'WTF3',
 'AB4',
 'ABG',
 'AC2',
 'AT4',
 'AT6',
 'BC1',
 'BC2',
 'BCR',
 'BGH',
 'BGK',
 'CW1',
 'CW2',
 'CWH',
 'DTM',
 'EDC',
 'F1K',
 'FDK',
 'FR2',
 'FRK',
 'FRT',
 'GC1',
 'GC2',
 'GR1',
 'GR2',
 'GU2',
 'KA2',
 'KA4',
 'KA6',
 'KAT',
 'KR1',
 'KR2',
 'KR3',
 'KR4',
 'KR6',
 'KS2',
 'KVS',
 'KW2',
 'KYT',
 'MB2',
 'MT2',
 'MT5',
 'MTT',
 'OW2',
 'OWG',
 'OWI',
 'P1G',
 'P1P',
 'P2G',
 'P2P',
 'PB2',
 'PP2',
 'PPP',
 'PPS',
 'PPT',
 'RCV',
 'RJ2',
 'RTV',
 'RXV',
 'SG5',
 'SG7',
 'SH2',
 'SHH',
 'SK2',
 'SKT',
 'SKV',
 'SP2',
 'SUT',
 'TB2',
 'TB4',
 'TR1',
 'TR2',
 'UNI',
 'W&F',
 'WS1',
 'WS2',
 'YAS',
 'YEP',
 'YHD',
 'AB',
 'BG',
 'F1',
 'F2',
 'FD',
 'FR',
 'GU',
 'ID',
 'KS',
 'KW',
 'MB',
 'MT',
 'P1',
 'P2',
 'PB',
 'PH',
 'PP',
 'PS',
 'RC',
 'RJ',
 'RS',
 'RT',
 'RX',
 'S2',
 'SC',
 'SH',
 'SK',
 'SP',
 'ST',
 'TB',
 'TR',
 'TX',
 'UC',
 'UN',
 'VD',
 'S']

In [105]:
def separate_prefix_number(row):
    
    pl = all_prefix_sort
    #print(pl)
    v = row['code']
    if row['prefix'] == '':
        not_find = True
        amo_id = row['amo_id']
        
        for el in pl:
            if el == row['code'][0:len(el)]:
#                 print(el, row['code'][0:len(el)], row['code'])
            #if el in row['code']:
                try:
                    v = el + '_' + row['code'][len(el):]
#                     not_find = False
                except:
                    pass
                finally:
                    return v
#         if not_find:
        pl = prefix_amo   
        #print(pl)
        for el in pl:
            #print(el,row['code'][0:len(el)])
            if el == row['code'][0:len(el)]:
                #print(el, row['code'][0:len(el)+1], row['code'])
            #if el in row['code']:
                try:
                    v = el + '_' + row['code'][len(el):]
                except:
                    pass
                finally:
                    return v
    return v

In [106]:
df_amo_temp['code'] = df_amo_temp.apply(separate_prefix_number,axis=1)

In [107]:
df_amo_temp.head(5)

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number
0,660235,Успешно_реализовано,3290.0,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный_сертификатна_Квадроциклы_(Выберите_...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1_01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X1,01053659
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF20,95425
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT_116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
3,929931,Успешно_реализовано,7200.0,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,VWS60_22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VWS60,22477
4,938619,Успешно_реализовано,6000.0,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1_01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP2X1,01053332

In [108]:
df_amo_temp.loc[df_amo_temp['prefix'] == '','prefix'] = \
df_amo_temp['code'].apply(lambda x: re.split('[_]',x)[0] if ' ' in x or '_' in x else '')

In [109]:
df_amo_temp.loc[df_amo_temp['number'] == '','number'] = \
df_amo_temp['code'].apply(lambda x: re.split('[_]',x)[1] if ' ' in x or '_' in x else '')

In [110]:
df_amo_temp.head(5)

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number
0,660235,Успешно_реализовано,3290.0,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный_сертификатна_Квадроциклы_(Выберите_...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1_01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X1,01053659
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF20,95425
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT_116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,GRT,116593
3,929931,Успешно_реализовано,7200.0,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,VWS60_22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VWS60,22477
4,938619,Успешно_реализовано,6000.0,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1_01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP2X1,01053332

In [111]:
df_not_separate_prefix = df_amo_temp.loc[~df_amo_temp['code'].str.contains('_')]

In [112]:
df_not_separate_prefix.shape

(31, 25)

In [113]:
df_not_separate_prefix

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number
27,2966455,Успешно_реализовано,9350.0,2020-03-19 12:57:22,2020-07-10 18:33:00,NaN,NaN,NaN,NaN,NaN,8500.0,Вейксёрф_и_вейк_за_катером,42064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
44,4036001,Успешно_реализовано,4850.0,2020-03-27 12:13:24,2020-07-10 18:26:00,NaN,390,Подарочный_сертификатна_Искусственную_Волну_(В...,4850.0,4500.0,4850.0,Искусственная_волна,43220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
93,8122189,Успешно_реализовано,4350.0,2020-06-10 20:27:13,2020-06-15 11:14:00,NaN,NaN,NaN,NaN,NaN,4350.0,САП-сёрф,81826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
95,8142557,Успешно_реализовано,12345.0,2020-06-11 11:52:11,2020-06-12 13:11:00,NaN,NaN,NaN,NaN,NaN,12345.0,Универсальный_Мосвейк_12345,M&F23085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
118,8516711,Успешно_реализовано,3600.0,2020-06-20 16:28:47,2020-07-10 18:04:00,NaN,NaN,NaN,NaN,NaN,3600.0,Вейксёрф_и_вейк_за_катером,01213577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
129,8600581,Успешно_реализовано,8400.0,2020-06-23 12:40:41,2020-07-10 18:04:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,25579,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
319,9540233,Успешно_реализовано,3000.0,2020-07-18 19:33:14,2020-07-18 22:03:00,NaN,NaN,NaN,NaN,NaN,2700,Флайборд_/_Ховерборд_/_Ранец,M94336,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
394,9963485,Успешно_реализовано,4000.0,2020-07-31 14:47:26,2020-07-31 16:09:00,NaN,NaN,NaN,NaN,NaN,4000,САП-сёрф,W2SU2476076555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
589,11748177,Успешно_реализовано,4200.0,2020-09-22 22:52:46,2020-09-24 22:36:00,NaN,NaN,NaN,NaN,NaN,4200,Вейк-парк,60PARK97598,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-09-26,NaN,,,
781,15334621,Успешно_реализовано,16000.0,2021-01-16 11:34:50,2021-01-24 14:21:00,NaN,NaN,NaN,NaN,NaN,16000,Снегоходы,79934,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
784,15350229,Успешно_реализовано,8000.0,2021-01-17 13:10:49,2021-01-17 20:02:00,NaN,NaN,NaN,NaN,NaN,8000,Снегоходы,98173,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
824,15781389,Успешно_реализовано,4290.0,2021-02-03 12:26:25,2021-02-08 22:12:00,290.0,NaN,Подарочный_сертификат_на_квадроциклы_(Выберите...,4290.0,4000.0,4290,Квадроциклы,KVP1102024295,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2022-03-01,NaN,,,
963,16313257,Успешно_реализовано,10000.0,2021-02-23 12:40:20,2021-02-23 12:58:00,0.0,NaN,Подарочный_сертификатна_пилотаж_на_спортивном_...,10000.0,10000.0,10000,Авиа_Самолёты,VFMP30365043415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1034,16712559,Успешно_реализовано,242900.0,2021-03-12 14:18:19,2021-03-12 15:51:00,NaN,NaN,NaN,NaN,NaN,242900,NaN,90855,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1049,16808755,Успешно_реализовано,11500.0,2021-03-16 16:32:03,2021-03-16 17:09:00,0.0,NaN,Подарочный_сертификатна_прогулку_на_самолёте_C...,11500.0,11500.0,11500,Авиа_Самолёты,VFMCS45425046055,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1118,17354135,Успешно_реализовано,7400.0,2021-04-08 10:30:27,2021-04-08 21:55:00,400.0,NaN,Подарочный_сертификатна_Ховерборд_(Выберите_ти...,7400.0,7000.0,7400,Флайборд_/_Ховерборд_/_Ранец,H42255,NaN,HB20305,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1227,17947779,Успешно_реализовано,6000.0,2021-04-29 14:25:13,2021-05-06 11:52:00,0.0,NaN,Подарочный_сертификатна_Электробайк_(Выберите_...,6000.0,6000.0,6000,Мото_Электробайк,12931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1357,18581471,Успешно_реализовано,1600.0,2021-05-28 19:00:37,2021-05-28 19:16:00,0.0,NaN,Подарочный_сертификатна_Сап-Сёрфинг_(Выберите_...,1600.0,1600.0,1600,САП-сёрф,79532,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1389,18637653,Успешно_реализовано,4400.0,2021-06-01 11:11:08,2021-06-06 22:31:00,400.0,350,Подарочный_сертификатна_Квадроциклы_(Выберите_...,4400.0,4000.0,4400,Квадроциклы,KV1P1X102044120,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2022-01-20,NaN,,,
1496,18859675,Успешно_реализовано,4000.0,2021-06-11 16:25:28,2021-06-11 16:51:00,NaN,NaN,Подарочный_сертификатна_сап-сёрфинг_(Выберите_...,4000.0,NaN,4000,САП-сёрф,62127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1541,18978659,Успешно_реализовано,8200.0,2021-06-17 20:54:36,2021-06-27 11:50:00,290.0,480,Подарочный_сертификатна_вейк_за_катером_(Выбер...,8090.0,7800.0,8200,Вейксёрф_и_вейк_за_катером,66064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1752,19199281,Успешно_реализовано,4000.0,2021-07-05 19:28:04,2021-07-06 16:02:00,0.0,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,4000.0,4000.0,4000,Квадроциклы,KV1P1X102099687459,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1785,19237733,Успешно_реализовано,4400.0,2021-07-08 13:24:09,2021-07-09 00:58:00,400.0,527,Подарочный_сертификат_на_квадроциклы_(Выберите...,4400.0,4000.0,4400,Квадроциклы,KV1P1X102167289,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
1882,19333746,Успешно_реализовано,7500.0,2021-07-15 16:02:04,2021-07-20 15:58:00,0.0,NaN,Подарочный_сертификатна_прогулку_на_самолёте_C...,7500.0,7500.0,NaN,Авиа_Самолёты,36528,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
2356,19864137,Успешно_реализовано,12000.0,2021-09-17 13:59:03,2021-09-17 15:09:00,0.0,NaN,Подарочный_сертификатна_полёт_на_самолёте_(Выб...,12000.0,12000.0,12000,Авиа_Самолёты,VFMCS45037727,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
2419,20301050,Успешно_реализовано,3000.0,2021-11-07 10:52:02,2021-11-07 11:50:00,0.0,NaN,Подарочный_сертификатна_Электробайк_(Выберите_...,3000.0,3000.0,3000,Мото_Электробайк,32580,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
2872,21140213,Успешно_реализовано,4500.0,2022-02-16 14:59:06,2022-02-16 16:01:00,0.0,NaN,Подарочный_сертификат_на_Флайборд_(Выберите_ти...,4500.0,4500.0,4500,Флайборд_/_Ховерборд_/_Ранец,98915,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
3014,21311499,Успешно_реализовано,3500.0,2022-03-02 16:15:37,2022-03-04 21:23:00,0.0,NaN,Подарочный_сертификатна_ховерборд_(Выберите_ти...,3500.0,3500.0,3500,Флайборд_/_Ховерборд_/_Ранец,H54470,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,
3859,22078429,Успешно_реализовано,4000.0,2022-06-28 11:49:00,2022-06-28 20:02:00,400.0,NaN,Подарочный_сертификат_в_Вейк-парк_(Выберите_ти...,2400.0,2000.0,4000,Вейк-парк,WP19045770,NaN,SU60190183,NaN,NaN,NaN,NaN,Погашен,2022-07-10,NaN,,,
5592,24084549,Успешно_реализовано,5700.0,2023-04-15 21:38:45,2023-05-01 16:47:00,500.0,NaN,катание_на_картинге_(Варианты:_40_минут_катани...,5700.0,5200.0,5700,Картинг,52950,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,4400,,,
8245,26872373,Успешно_реализовано,0.0,2024-02-15 21:33:58,2024-02-16 10:33:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,19652,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,

In [114]:
df_amo_temp['code'] = df_amo_temp.apply(lambda x: re.sub(r'(W)(F)', r'\1&\2', x['code']),axis=1)

#### Дополнительное поле prefix_V для "чистых префиксов" (без V)

In [115]:
df_amo_temp['prefix'] = df_amo_temp.apply(lambda x: replace_cirillic_latin(x['prefix']),axis=1)

In [116]:
df_amo_temp['prefix_V'] = df_amo_temp['prefix']

In [117]:
df_amo_temp.loc[(df_amo_temp['prefix'].str[0] == 'V'),'prefix_V'] = df_amo_temp['prefix'].str[1:]

In [118]:
df_amo_temp.head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V
0,660235,Успешно_реализовано,3290.0,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный_сертификатна_Квадроциклы_(Выберите_...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1_01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X1,01053659,KVP1X1
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF20,95425,MF20
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT_116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,GRT,116593,GRT
3,929931,Успешно_реализовано,7200.0,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,VWS60_22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VWS60,22477,WS60
4,938619,Успешно_реализовано,6000.0,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1_01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP2X1,01053332,KVP2X1

#### Отсутствующие префиксы

In [119]:
prefix_amo = list(df_amo_temp['prefix_V'].unique())
prefix_amo.sort()
#prefix_amo = prefix_amo[1:]

##### Префиксы в AMO

In [120]:
print(prefix_amo)

['', '2SU24', '2SU60', '2WP24', '60WAKE', 'AC2', 'AC30', 'AC60', 'AT', 'AT10', 'AT15', 'AT30', 'AT4', 'AT4K', 'AT6', 'AT60', 'AT6K', 'AWP', 'BF180', 'BF40', 'BF90', 'BG', 'BGH', 'BGK', 'BGKH', 'CS20', 'CS30', 'CS40', 'CS60', 'CW1', 'CW1T', 'CW2', 'CW2T', 'CWH', 'D', 'DRC2H', 'DRCH', 'DT230', 'DT240', 'DT260', 'DT30', 'DT32', 'DT40', 'DT42', 'DT60', 'DT62', 'DTM', 'EB1X', 'EB1X1', 'EB2X', 'ED3H', 'EDC', 'EF30', 'EF60', 'EFL', 'EFL30', 'EFL60', 'ES130', 'ES160', 'ES230', 'ES260', 'ESG1', 'ESG2', 'F1', 'FJ30', 'FM30', 'FM45', 'FM60', 'FMCS30', 'FMCS45R', 'FMP30', 'FR', 'FR2', 'FRT', 'GC1', 'GC2', 'GR1', 'GR1X1', 'GR2', 'GR2X1', 'GRT', 'GU', 'GU2', 'HB20', 'HB30', 'HB60', 'HY30', 'HY30T', 'HY60', 'HY60T30', 'JT2', 'JT4A', 'KA2', 'KA4', 'KA6', 'KAT', 'KAT2', 'KAT4', 'KR1', 'KR2', 'KR3', 'KR4', 'KS', 'KS2', 'KV1X', 'KV1X1', 'KV2X1', 'KVC', 'KVP1X', 'KVP1X1', 'KVP1X2', 'KVP2X1', 'KVS', 'LB1X', 'LL1H', 'LL1HP', 'LL2H', 'LL3H', 'MB', 'MB2', 'MB2X', 'MF', 'MF20', 'MF30', 'MF30134139', 'MF306120784', 'MF60', 'MMF20', 'MMF30', 'MMF60', 'MSU60', 'MT', 'MT10', 'MT2', 'MT2B', 'MT5', 'MTT', 'MW&F', 'MWP15', 'MWS1', 'MWS2', 'MWS25', 'MWS40', 'MWSN40', 'P1', 'P1G', 'P1P', 'P2', 'P2G', 'PB', 'PB2', 'PB2X', 'PH', 'PH20', 'PL15', 'PL20', 'PP', 'PP2', 'PP2P', 'PP2S', 'PPP', 'PPS', 'PPT', 'PR20', 'PR30', 'PR40', 'PR60', 'PS', 'RB15', 'RB20', 'RB30', 'RB40', 'RC', 'RCV', 'RJ', 'RJ1X', 'RJ2', 'RJ2X', 'RS', 'RTV', 'RX', 'RXV', 'S', 'S2', 'SG10', 'SG5', 'SG7', 'SH', 'SH2', 'SHH', 'SK', 'SK2', 'SK2V', 'SKI20', 'SKI40', 'SKI40T', 'SKI60', 'SKI60T', 'SKT', 'SKT1', 'SKT2', 'SKT4', 'SKV', 'SN1X', 'SN1X1', 'SN2X', 'SN2X1', 'SN2X4', 'SN60', 'SP', 'SP2', 'ST', 'SU24', 'SU60', 'SUT', 'SVH', 'TB2', 'TR', 'TR1', 'TR1K', 'TR2', 'TR2K', 'TR30', 'UN', 'W&F', 'WF', 'WP15', 'WP24', 'WP2H', 'WP30', 'WP60', 'WPA', 'WS', 'WS1', 'WS20', 'WS20T', 'WS20TR', 'WS25', 'WS30', 'WS30T', 'WS40', 'WS40T', 'WS6', 'WS60', 'WS60T', 'WSN25', 'WSN40', 'WSN40T', 'WSN60', 'WSN60T', 'WTF', 'WTF2', 'WTF3', 'YAS', 'YEP']

##### Префиксы, отсутсвующие в общем списке

In [121]:
#missing_prefix = set(prefix_value).difference(set(prefix_amo))
missing_prefix = list(set(prefix_amo)-(set(all_prefix)))
missing_prefix.sort()

In [122]:
print(missing_prefix)

['', '60WAKE', 'AT', 'AWP', 'D', 'EFL', 'GRT', 'HY30T', 'HY60T30', 'JT2', 'JT4A', 'KV1X', 'KVC', 'KVP1X', 'KVP1X2', 'MF', 'MF30134139', 'MF306120784', 'PH20', 'SKI40T', 'SKI60T', 'SN2X4', 'SN60', 'SVH', 'TR30', 'WF', 'WP24', 'WPA', 'WS', 'WS20T', 'WS20TR', 'WS30T', 'WS40T', 'WS6', 'WS60T', 'WSN40T', 'WSN60T', 'WTF']

In [123]:
len(missing_prefix)

38

In [124]:
print('AT'=='AT')

True

#### Товары, префиксы которых отсутствуют в списке категорий

In [125]:
df_amo_missing_prefix = df_amo_temp.query('prefix in @missing_prefix')

In [126]:
df_amo_missing_prefix.head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT_116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,GRT,116593,GRT
6,1058967,Успешно_реализовано,2750.0,2020-03-05 10:42:16,2020-03-08 05:05:00,NaN,NaN,Подарочный_сертификат_в_крытый_Вейк-парк_(Выбе...,2750.0,2750.0,NaN,NaN,GRT_232948,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,GRT,232948,GRT
18,2043485,Успешно_реализовано,8000.0,2020-03-12 16:42:41,2020-03-12 16:45:00,NaN,NaN,NaN,NaN,NaN,8000.0,Квадроциклы,KVP1X2_???96384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X2,???96384,KVP1X2
27,2966455,Успешно_реализовано,9350.0,2020-03-19 12:57:22,2020-07-10 18:33:00,NaN,NaN,NaN,NaN,NaN,8500.0,Вейксёрф_и_вейк_за_катером,42064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,,
44,4036001,Успешно_реализовано,4850.0,2020-03-27 12:13:24,2020-07-10 18:26:00,NaN,390,Подарочный_сертификатна_Искусственную_Волну_(В...,4850.0,4500.0,4850.0,Искусственная_волна,43220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,,

In [127]:
df_amo_missing_prefix.shape

(228, 26)

Количество записей для префиксов, отсутствующих в общей базе

In [128]:
df_amo_missing_prefix.groupby(['prefix'])['prefix'].count()

prefix
               31
60WAKE          6
AT              1
GRT             2
JT2             1
KVC             1
KVP1X2          1
MF              1
MF30134139      1
WF            181
WP24            1
WS30T           1
Name: prefix, dtype: int64

In [129]:
df111 = df_amo_temp.query('prefix == "MF"')

In [130]:
df111.head(10)

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V
6622,24790553,Успешно_реализовано,0.0,2023-07-11 21:16:07,2023-07-14 10:52:00,NaN,NaN,NaN,NaN,NaN,0,Флайборд_/_Ховерборд_/_Ранец,MF_2521379,#24790463,NaN,NaN,NaN,NaN,NaN,NaN,NaT,5525,,MF,2521379,MF

Префиксу WF соответствует W&F

In [131]:
df_amo_temp.loc[df_amo_temp['prefix_V'] == 'WF','prefix_V'] = 'W&F'

In [132]:
df_amo_temp.loc[df_amo_temp['prefix'] == 'WF','prefix'] = 'W&F'

In [133]:
df_amo_temp.loc[df_amo_temp['prefix'] == 'VWF','prefix'] = 'VW&F'

#### База АМО без prefix

In [134]:
df_amo_without_prefix = df_amo_temp.loc[df_amo_temp['prefix'] == '']

In [135]:
df_amo_without_prefix.shape

(31, 26)

In [136]:
df_amo_without_prefix.head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V
27,2966455,Успешно_реализовано,9350.0,2020-03-19 12:57:22,2020-07-10 18:33:00,NaN,NaN,NaN,NaN,NaN,8500.0,Вейксёрф_и_вейк_за_катером,42064,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,,
44,4036001,Успешно_реализовано,4850.0,2020-03-27 12:13:24,2020-07-10 18:26:00,NaN,390,Подарочный_сертификатна_Искусственную_Волну_(В...,4850.0,4500.0,4850.0,Искусственная_волна,43220,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,,
93,8122189,Успешно_реализовано,4350.0,2020-06-10 20:27:13,2020-06-15 11:14:00,NaN,NaN,NaN,NaN,NaN,4350.0,САП-сёрф,81826,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,,
95,8142557,Успешно_реализовано,12345.0,2020-06-11 11:52:11,2020-06-12 13:11:00,NaN,NaN,NaN,NaN,NaN,12345.0,Универсальный_Мосвейк_12345,M&F23085,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,,
118,8516711,Успешно_реализовано,3600.0,2020-06-20 16:28:47,2020-07-10 18:04:00,NaN,NaN,NaN,NaN,NaN,3600.0,Вейксёрф_и_вейк_за_катером,01213577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,,,

In [137]:
#df_amo_temp = df_amo_temp.loc[df_amo_temp['prefix'] != '']

In [138]:
df_amo_temp['card_type'] ='paper'

In [139]:
#df_amo_temp['series'] =''

In [140]:
df_amo_temp['design_type'] = 'design1'

In [141]:
df_amo_temp['status'] = ''

In [142]:
#df_amo_temp['stock_status'] = ''

In [143]:
df_amo_temp['sale_price'] = 0

In [144]:
df_amo_temp['expiry_date'] = ''

In [145]:
df_amo_temp['created_at'] = ''

In [146]:
df_amo_temp['updated_at'] = ''

In [147]:
df_amo_temp['deleted_at'] = ''

In [148]:
df_amo_temp.loc[(df_amo_temp['card_used_date'].notna()) |  (df_amo_temp['статус_погашения'] == 'Погашен'),'status'] = 'sold_used'

In [149]:
df_amo_temp['supplier_payment_date'] = df_amo_temp['card_used_date']

In [150]:
df_amo_temp.query('status=="sold_used"').head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V,card_type,design_type,status,sale_price,expiry_date,created_at,updated_at,deleted_at,supplier_payment_date
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF20,95425,MF20,paper,design1,sold_used,0,,,,,2020-07-01
5,948101,Успешно_реализовано,5290.0,2020-03-04 17:11:49,2020-07-10 18:34:00,NaN,NaN,Подарочный_сертификатна_Сап-Сёрфинг_(Выберите_...,5290.0,5000.0,NaN,САП-сёрф,SU24_43411,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-08-09,NaN,,SU24,43411,SU24,paper,design1,sold_used,0,,,,,2020-08-09
17,2043465,Успешно_реализовано,7290.0,2020-03-12 16:42:41,2020-07-10 18:34:00,NaN,290,NaN,NaN,NaN,NaN,Флайборд_/_Ховерборд_/_Ранец,MF60_61004,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF60,61004,MF60,paper,design1,sold_used,0,,,,,2020-07-01
19,2043467,Успешно_реализовано,4250.0,2020-03-12 16:42:41,2020-07-10 18:34:00,NaN,0,NaN,NaN,NaN,4250.0,Вейксёрф_и_вейк_за_катером,GR1X1_01015399,NaN,PH017,NaN,NaN,NaN,NaN,Погашен,NaT,NaN,,GR1X1,01015399,GR1X1,paper,design1,sold_used,0,,,,,NaT
20,2043469,Успешно_реализовано,12745.0,2020-03-12 16:42:41,2020-07-10 18:33:00,NaN,400,NaN,NaN,NaN,NaN,Универсальный_Мосвейк_12345,W&F_89033,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2023-08-04,NaN,,W&F,89033,W&F,paper,design1,sold_used,0,,,,,2023-08-04

In [151]:
df_amo_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9176 entries, 0 to 9175
Data columns (total 35 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   amo_id                         9176 non-null   int64
 1   этап_сделки                    8368 non-null   object
 2   бюджет                         8368 non-null   float64
 3   дата_создания_сделки           9176 non-null   datetime64[ns]
 4   sale_date                      9176 non-null   datetime64[ns]
 5   delivery_price                 5614 non-null   float64
 6   стоимость_доставки             504 non-null    object
 7   products                       7449 non-null   object
 8   price                          7449 non-null   float64
 9   subtotal                       8213 non-null   float64
 10  выручка_от_клиента             8162 non-null   object
 11  направление_(вид_сертификата)  9054 non-null   object
 12  code                           9176 non-null   object
 13  корневая_сделка                159 non-null    object
 14  номер_2-го_сертификата         714 non-null    object
 15  номер_3-го_сертификата         10 non-null     object
 16  номер_4-го_сертификата         4 non-null      object
 17  номер_5-го_сертификата         27 non-null     object
 18  сертификат_на_тренера          112 non-null    object
 19  статус_погашения               3288 non-null   object
 20  card_used_date                 3259 non-null   datetime64[ns]
 21  стоимость_закупки              2715 non-null   object
 22  id                             9176 non-null   object
 23  prefix                         9176 non-null   object
 24  number                         9176 non-null   object
 25  prefix_V                       9176 non-null   object
 26  card_type                      9176 non-null   object
 27  design_type                    9176 non-null   object
 28  status                         9176 non-null   object
 29  sale_price                     9176 non-null   int64
 30  expiry_date                    9176 non-null   object
 31  created_at                     9176 non-null   object
 32  updated_at                     9176 non-null   object
 33  deleted_at                     9176 non-null   object
 34  supplier_payment_date          3259 non-null   datetime64[ns]
dtypes: datetime64[ns](4), float64(4), int64(2), object(25)
memory usage: 2.8+ MB

### Обработка поля **status**

In [152]:
df_amo_temp.loc[(df_amo_temp['card_used_date'].notna()) |  \
                (df_amo_temp['статус_погашения'] == 'Погашен'),'status'] = 'sold_used'

### Обработка **sale_price**

#### Строки, являющиеся корневыми сделками

In [153]:
lst_root_deal = list(df_amo_temp.query('корневая_сделка.notna()')['корневая_сделка'])

In [154]:
print(lst_root_deal)

['VMT2_2416017', '#23018371', '#23041919', '#23045841', '#23245257', '23285275', '#23287451', '#23307809', '23320675', '23371033', '#23379527', '#23381609', '#23459729', '1715029001', '#23586703', '#23514709', '#23624295', '#23624295', '#23624295', '#23681147', '#23681147', '#23705733', '#23703937', '#23710155', '#23716727', '#23716727', '#23716727', '23717485', '23718601', '23718601', '23718601', '#23724197', '#23723181', '23727459', '#23728823', '#23729565', '#23729565', '#23729565', '23732757', '#23720975', '#23748665', '#23756947', '#23769895', '#23772175', '#23787591', '#23760001', '#23906061', '#23918309', '#23918309', '23923847', '23923847', '#23931737', '23963847', '#23968933', '#23965909', '#24029505', '24030407', '#24072407', '#24083997', '#24098553', '#24103527', '24108151', '#24122097', 'КR2_230212', '#24177302', '#24204699', '24214499', '24292405', '#24294657', '#24308743', '24349847', '24378991', '#24386001', '24402725', '24403171', '24403285', '24432999', '24434571', '24436793', '24437073', '24526869', '#24543987', '24548805', '#24579543', '#24579543', '#24579543', '#24579543', '#24586559', '#24606011', '#24621605', '#24646105', '#24651727', '24669423', '24676465', '#24678867', '#24693067', '#24696037', '#24696037', '#24715547', '24723003', '24740295', '24757173', '24757173', '#24770321', '24733567', '#24790463', '#24815607', '#24817501', '#24818493', '24819955', '24864753', '#24873289', '24906299', '24930467', '24930467', '#24935145', '#24955825', '#24964891', '#24975785', '24992009', '#24996157', '#25010665', '#25010665', '#25010665', '#25011851', '25022279', '25027311', '24996969', '24996969', '#25070099', '25084249', '25084249', '25141043', '25156349', '25156349', '#25228541', '25256899', '25256899', '#25269385', '#25538207', '#25538207', '#25693371', '#25885733', '#25938825', '#25988183', '#26042871', '#26139623', '#26171801', '#26287915', '#26322051', '#26357639', '#26365001', '#26365511', '#26386633', '#26405057', '#26406417', '26432777', '26432777', '26459569']

In [155]:
len(lst_root_deal)

159

In [156]:
def clear_num(num):
    """
    Очистка id корневой сделки и перевод ео в int
    """
    if num.isdigit():
        return int(num)
    else:
        l = len(num)-1
        while l>0:
            if num[l].isdigit():
                l -= 1
            else:
                break
        return int(num[l+1:])

Проверка:

In [157]:
print(clear_num('КR2_230212'))

230212

In [158]:
lst_root_deal = list(map(clear_num,lst_root_deal))

Список id строк, являющимися корневыми сделками

In [159]:
print(lst_root_deal)

[2416017, 23018371, 23041919, 23045841, 23245257, 23285275, 23287451, 23307809, 23320675, 23371033, 23379527, 23381609, 23459729, 1715029001, 23586703, 23514709, 23624295, 23624295, 23624295, 23681147, 23681147, 23705733, 23703937, 23710155, 23716727, 23716727, 23716727, 23717485, 23718601, 23718601, 23718601, 23724197, 23723181, 23727459, 23728823, 23729565, 23729565, 23729565, 23732757, 23720975, 23748665, 23756947, 23769895, 23772175, 23787591, 23760001, 23906061, 23918309, 23918309, 23923847, 23923847, 23931737, 23963847, 23968933, 23965909, 24029505, 24030407, 24072407, 24083997, 24098553, 24103527, 24108151, 24122097, 230212, 24177302, 24204699, 24214499, 24292405, 24294657, 24308743, 24349847, 24378991, 24386001, 24402725, 24403171, 24403285, 24432999, 24434571, 24436793, 24437073, 24526869, 24543987, 24548805, 24579543, 24579543, 24579543, 24579543, 24586559, 24606011, 24621605, 24646105, 24651727, 24669423, 24676465, 24678867, 24693067, 24696037, 24696037, 24715547, 24723003, 24740295, 24757173, 24757173, 24770321, 24733567, 24790463, 24815607, 24817501, 24818493, 24819955, 24864753, 24873289, 24906299, 24930467, 24930467, 24935145, 24955825, 24964891, 24975785, 24992009, 24996157, 25010665, 25010665, 25010665, 25011851, 25022279, 25027311, 24996969, 24996969, 25070099, 25084249, 25084249, 25141043, 25156349, 25156349, 25228541, 25256899, 25256899, 25269385, 25538207, 25538207, 25693371, 25885733, 25938825, 25988183, 26042871, 26139623, 26171801, 26287915, 26322051, 26357639, 26365001, 26365511, 26386633, 26405057, 26406417, 26432777, 26432777, 26459569]

In [160]:
df_amo_temp.query('amo_id in @lst_root_deal').head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V,card_type,design_type,status,sale_price,expiry_date,created_at,updated_at,deleted_at,supplier_payment_date
4782,23018371,Успешно_реализовано,10350.0,2022-11-07 12:40:42,2022-11-08 19:32:00,350.0,NaN,Мотокросс_и_Эндуро_(Варианты:_2_часа_с_тренеро...,10350.0,10000.0,10350,Мото_Мотокросс,MT2B_20013189,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,4000,,MT2B,20013189,MT2B,paper,design1,,0,,,,,NaT
4786,23041919,Успешно_реализовано,8000.0,2022-11-10 14:37:31,2022-11-10 20:29:00,NaN,NaN,"Электробайк_(Варианты:_1,5_ч_катания_для_1_чел...",8000.0,8000.0,8000,Мото_Электробайк,VEB1X_221430938,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2023-04-09,3200,,VEB1X,221430938,EB1X,paper,design1,sold_used,0,,,,,2023-04-09
4791,23045841,Успешно_реализовано,16900.0,2022-11-11 09:18:21,2022-11-11 16:41:00,400.0,NaN,Полет_на_параплане_(Варианты:_2_полета_с_инстр...,16900.0,16500.0,16900,Параплан,P2_22088724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,5500,,P2,22088724,P2,paper,design1,,0,,,,,NaT
4836,23245257,Успешно_реализовано,9900.0,2022-12-06 11:29:01,2022-12-07 20:38:00,400.0,207,Квадроциклы_(Варианты:_1_квадрик_1_час_без_пас...,9900.0,9500.0,9900,Снегоходы,SN1X_19054346,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2023-02-18,4000,,SN1X,19054346,SN1X,paper,design1,sold_used,0,,,,,2023-02-18
4853,23285275,Успешно_реализовано,18000.0,2022-12-12 13:17:25,2022-12-15 13:47:00,0.0,NaN,"Снегоходы_(Варианты:_1_снежик_на_2_часа,_Бумаж...",18000.0,18000.0,18000,Снегоходы,SN2X1_17024919,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2023-02-20,16000,,SN2X1,17024919,SN2X1,paper,design1,sold_used,0,,,,,2023-02-20

Если в сделке 1 товар и сделка не имеет производных сделок, то использовать значение поля SUBTOTAL

#### Расчет sale_price для обычных товаров

In [161]:
# df_amo_temp.loc[(df_amo_temp['номер_2-го_сертификата'].isna()) & \
#                 (df_amo_temp['номер_3-го_сертификата'].isna()) & \
#                 (df_amo_temp['номер_4-го_сертификата'].isna()) & \
#                 (df_amo_temp['номер_5-го_сертификата'].isna()) & \
#                 (df_amo_temp['сертификат_на_тренера'].isna()) &\
#                 (~df_amo_temp['amo_id'].isin(lst_root_deal)) &\
#                 (df_amo_temp['корневая_сделка'].isna()),\
#                 'sale_price'] = df_amo_temp['subtotal']

In [162]:
df_amo_temp.loc[(df_amo_temp['номер_2-го_сертификата'].isna()) & \
                (df_amo_temp['номер_3-го_сертификата'].isna()) & \
                (df_amo_temp['номер_4-го_сертификата'].isna()) & \
                (df_amo_temp['номер_5-го_сертификата'].isna()) & \
                (df_amo_temp['сертификат_на_тренера'].isna()) &\
                (~df_amo_temp['amo_id'].isin(lst_root_deal)),\
                'sale_price'] = df_amo_temp['subtotal']

Проверка

Сумма поля sale_price для сделок, являющихся корневыми

In [163]:
df_amo_temp.query('amo_id in @lst_root_deal')['sale_price'].sum()

0.0

Сумма поля sale_price для сделок, не являющихся корневыми, не имеющих дополнительных серт

In [164]:
dd = df_amo_temp.loc[(df_amo_temp['номер_2-го_сертификата'].isna()) & \
                (df_amo_temp['номер_3-го_сертификата'].isna()) & \
                (df_amo_temp['номер_4-го_сертификата'].isna()) & \
                (df_amo_temp['номер_5-го_сертификата'].isna()) & \
                (df_amo_temp['сертификат_на_тренера'].isna()) &\
                (~df_amo_temp['amo_id'].isin(lst_root_deal))]

In [165]:
dd.head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V,card_type,design_type,status,sale_price,expiry_date,created_at,updated_at,deleted_at,supplier_payment_date
0,660235,Успешно_реализовано,3290.0,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный_сертификатна_Квадроциклы_(Выберите_...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1_01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X1,01053659,KVP1X1,paper,design1,,3000.0,,,,,NaT
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF20,95425,MF20,paper,design1,sold_used,2600.0,,,,,2020-07-01
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT_116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,GRT,116593,GRT,paper,design1,,NaN,,,,,NaT
3,929931,Успешно_реализовано,7200.0,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,VWS60_22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VWS60,22477,WS60,paper,design1,,NaN,,,,,NaT
4,938619,Успешно_реализовано,6000.0,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1_01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP2X1,01053332,KVP2X1,paper,design1,,6000.0,,,,,NaT

In [166]:
dd['subtotal'].sum()

44828847.0

In [167]:
dd['sale_price'].sum()

44828847.0

In [168]:
df_amo_temp.head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V,card_type,design_type,status,sale_price,expiry_date,created_at,updated_at,deleted_at,supplier_payment_date
0,660235,Успешно_реализовано,3290.0,2020-03-02 14:59:05,2020-07-10 10:39:00,NaN,436,Подарочный_сертификатна_Квадроциклы_(Выберите_...,3290.0,3000.0,NaN,Квадроциклы,KVP1X1_01053659,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X1,01053659,KVP1X1,paper,design1,,3000.0,,,,,NaT
1,667573,Успешно_реализовано,2600.0,2020-03-02 15:39:28,2020-07-10 10:40:00,NaN,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,2600.0,2600.0,NaN,Флайборд_/_Ховерборд_/_Ранец,MF20_95425,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2020-07-01,NaN,,MF20,95425,MF20,paper,design1,sold_used,2600.0,,,,,2020-07-01
2,929417,Успешно_реализовано,3040.0,2020-03-04 12:51:10,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GRT_116593,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,GRT,116593,GRT,paper,design1,,NaN,,,,,NaT
3,929931,Успешно_реализовано,7200.0,2020-03-04 13:06:52,2020-07-10 18:34:00,NaN,NaN,NaN,NaN,NaN,NaN,Вейксёрф_и_вейк_за_катером,VWS60_22477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VWS60,22477,WS60,paper,design1,,NaN,,,,,NaT
4,938619,Успешно_реализовано,6000.0,2020-03-04 14:22:26,2020-03-08 05:06:00,NaN,NaN,Подарочный_сертификатна_Квадроциклы_(Выберите_...,6000.0,6000.0,NaN,Квадроциклы,KVP2X1_01053332,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP2X1,01053332,KVP2X1,paper,design1,,6000.0,,,,,NaT

База АМО c prefix

In [169]:
df_amo_temp = df_amo_temp.loc[df_amo_temp['prefix'] != '']

In [170]:
df_amo_temp.shape

(9145, 35)

In [171]:
df_amo_temp['card_type'] = df_amo_temp['prefix'].apply(lambda x: 'electronic' if x[0] == 'V' else 'paper')

In [172]:
df_amo_temp.query('amo_id==26139623').head()

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V,card_type,design_type,status,sale_price,expiry_date,created_at,updated_at,deleted_at,supplier_payment_date
7636,26139623,Успешно_реализовано,11450.0,2023-11-28 13:06:38,2023-12-02 22:29:00,450.0,NaN,"Снегоходы_(Варианты:_1_снежик_на_1_час,_Бумажн...",11450.0,11000.0,11450,Снегоходы,SN1X_19010652,NaN,SN1X_191480,NaN,NaN,NaN,NaN,Погашен,2024-02-11,4000,,SN1X,19010652,SN1X,paper,design1,sold_used,0.0,,,,,2024-02-11
8986,26139623,NaN,NaN,2023-11-28 13:06:38,2023-12-02 22:29:00,NaN,NaN,NaN,NaN,0.0,NaN,,SN1X_191480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,SN1X,191480,SN1X,paper,design1,,0.0,,,,,NaT

#### Расчет sale_price для корневых, имеющих дополнительные сертификаты

In [173]:
df_amo_temp['sale_price'].fillna(0, inplace=True)

In [174]:
df_amo_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9145 entries, 0 to 9175
Data columns (total 35 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   amo_id                         9145 non-null   int64
 1   этап_сделки                    8337 non-null   object
 2   бюджет                         8337 non-null   float64
 3   дата_создания_сделки           9145 non-null   datetime64[ns]
 4   sale_date                      9145 non-null   datetime64[ns]
 5   delivery_price                 5597 non-null   float64
 6   стоимость_доставки             500 non-null    object
 7   products                       7430 non-null   object
 8   price                          7430 non-null   float64
 9   subtotal                       8195 non-null   float64
 10  выручка_от_клиента             8134 non-null   object
 11  направление_(вид_сертификата)  9025 non-null   object
 12  code                           9145 non-null   object
 13  корневая_сделка                159 non-null    object
 14  номер_2-го_сертификата         712 non-null    object
 15  номер_3-го_сертификата         10 non-null     object
 16  номер_4-го_сертификата         4 non-null      object
 17  номер_5-го_сертификата         27 non-null     object
 18  сертификат_на_тренера          112 non-null    object
 19  статус_погашения               3284 non-null   object
 20  card_used_date                 3255 non-null   datetime64[ns]
 21  стоимость_закупки              2714 non-null   object
 22  id                             9145 non-null   object
 23  prefix                         9145 non-null   object
 24  number                         9145 non-null   object
 25  prefix_V                       9145 non-null   object
 26  card_type                      9145 non-null   object
 27  design_type                    9145 non-null   object
 28  status                         9145 non-null   object
 29  sale_price                     9145 non-null   float64
 30  expiry_date                    9145 non-null   object
 31  created_at                     9145 non-null   object
 32  updated_at                     9145 non-null   object
 33  deleted_at                     9145 non-null   object
 34  supplier_payment_date          3255 non-null   datetime64[ns]
dtypes: datetime64[ns](4), float64(5), int64(1), object(25)
memory usage: 2.5+ MB

Функция для определения sale_price для

In [175]:
def insert_sale111(row):    
    v = row['sale_price']
    if row['sale_price'] == 0:
        amo_id = row['amo_id']
        pr = row['prefix']
        v = 0
        str1 = f'sale_price != 0 & prefix == "{pr}"'
        try:
            v = df_amo_temp.query(str1).iloc[-1]['sale_price']
        except:
            pass
        finally:
            return v
    return v

In [176]:
def insert_sale(row):    
    v = row['sale_price']
    #print(v)
    if row['sale_price'] == 0:
        d = row['дата_создания_сделки']
        amo_id = row['amo_id']
        pr = row['prefix']
        #v = 0
        str1 = f'sale_price != 0 & prefix == "{pr}"'
        try:
            #v = df_amo_temp.query(str1).iloc[-1]['sale_price']
            arr = df_amo_temp.query(str1)    
            arr['diff_date'] = arr['дата_создания_сделки'] - d
            arr = arr.sort_values(by='diff_date',ascending=True)
            arr.reset_index(drop= True , inplace= True)
            v = arr.iloc[0]['sale_price']
            
        except:
            pass
        finally:
            return v
    return v

In [177]:
def insert_saleV(row):    
    v = row['sale_price']
    #print(v)
    if row['sale_price'] == 0:
        d = row['дата_создания_сделки']
        amo_id = row['amo_id']
        pr = row['prefix_V']
        #v = 0
        str1 = f'sale_price != 0 & prefix_V == "{pr}"'
        try:
            #v = df_amo_temp.query(str1).iloc[-1]['sale_price']
            arr = df_amo_temp.query(str1)    
            arr['diff_date'] = arr['дата_создания_сделки'] - d
            arr = arr.sort_values(by='diff_date',ascending=True)
            arr.reset_index(drop= True , inplace= True)
            v = arr.iloc[0]['sale_price']
            
        except:
            pass
        finally:
            return v
    return v

In [178]:
df_amo_temp['sale_price'] = df_amo_temp.apply(insert_sale,axis=1)

In [179]:
df_amo_temp['sale_price'] = df_amo_temp.apply(insert_saleV,axis=1)

Проверка:

In [180]:
pp = df_amo_temp.query('amo_id == 26139623')

In [181]:
pp

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V,card_type,design_type,status,sale_price,expiry_date,created_at,updated_at,deleted_at,supplier_payment_date
7636,26139623,Успешно_реализовано,11450.0,2023-11-28 13:06:38,2023-12-02 22:29:00,450.0,NaN,"Снегоходы_(Варианты:_1_снежик_на_1_час,_Бумажн...",11450.0,11000.0,11450,Снегоходы,SN1X_19010652,NaN,SN1X_191480,NaN,NaN,NaN,NaN,Погашен,2024-02-11,4000,,SN1X,19010652,SN1X,paper,design1,sold_used,5000.0,,,,,2024-02-11
8986,26139623,NaN,NaN,2023-11-28 13:06:38,2023-12-02 22:29:00,NaN,NaN,NaN,NaN,0.0,NaN,,SN1X_191480,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,SN1X,191480,SN1X,paper,design1,,5000.0,,,,,NaT

sale_price появился

#### Строки, оставшиеся без sale_price

In [182]:
dd0 = df_amo_temp.query('sale_price == 0')

In [183]:
dd0.shape

(326, 35)

In [184]:
dd0.head(10)

,amo_id,этап_сделки,бюджет,дата_создания_сделки,sale_date,delivery_price,стоимость_доставки,products,price,subtotal,выручка_от_клиента,направление_(вид_сертификата),code,корневая_сделка,номер_2-го_сертификата,номер_3-го_сертификата,номер_4-го_сертификата,номер_5-го_сертификата,сертификат_на_тренера,статус_погашения,card_used_date,стоимость_закупки,id,prefix,number,prefix_V,card_type,design_type,status,sale_price,expiry_date,created_at,updated_at,deleted_at,supplier_payment_date
18,2043485,Успешно_реализовано,8000.0,2020-03-12 16:42:41,2020-03-12 16:45:00,NaN,NaN,NaN,NaN,NaN,8000.0,Квадроциклы,KVP1X2_???96384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KVP1X2,???96384,KVP1X2,paper,design1,,0.0,,,,,NaT
132,8633971,Успешно_реализовано,5350.0,2020-06-23 16:04:00,2020-07-10 18:03:00,NaN,NaN,NaN,NaN,NaN,5350.0,Вейк-парк,WP24_46355,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2022-08-04,NaN,,WP24,46355,WP24,paper,design1,sold_used,0.0,,,,,2022-08-04
528,10821667,Успешно_реализовано,4000.0,2020-08-26 10:58:02,2020-08-26 11:15:00,NaN,NaN,NaN,NaN,NaN,4000,Тренер,VTR2K_138066338,NaN,VTR2K1390277,NaN,NaN,NaN,NaN,Погашен,2021-11-04,NaN,,VTR2K,138066338,TR2K,electronic,design1,sold_used,0.0,,,,,2021-11-04
571,11187459,Успешно_реализовано,1.0,2020-09-06 22:09:43,2020-09-06 22:15:00,NaN,NaN,NaN,NaN,NaN,1,Вейк-парк,WP30_04071533,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,WP30,04071533,WP30,paper,design1,,0.0,,,,,NaT
572,11187473,Успешно_реализовано,1.0,2020-09-06 22:11:22,2020-09-06 22:15:00,NaN,NaN,NaN,NaN,NaN,1,Вейк-парк,WP30_04092000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,WP30,04092000,WP30,paper,design1,,0.0,,,,,NaT
796,15499835,Успешно_реализовано,12000.0,2021-01-20 14:37:07,2021-01-23 07:40:00,NaN,NaN,NaN,NaN,NaN,12000,Аэротруба,AT_1007189075,NaN,PH027,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,AT,1007189075,AT,paper,design1,,0.0,,,,,NaT
1407,18695607,Успешно_реализовано,7500.0,2021-06-03 22:11:29,2021-06-04 07:33:00,NaN,NaN,Подарочный_сертификатна_вейксёрфинг_(Выберите_...,7500.0,NaN,7500,Вейксёрф_и_вейк_за_катером,VWS6_0584073507,NaN,NaN,NaN,NaN,NaN,NaN,Погашен,2021-11-24,NaN,,VWS6,0584073507,WS6,electronic,design1,sold_used,0.0,,,,,2021-11-24
1452,18769077,Успешно_реализовано,4500.0,2021-06-07 19:26:54,2021-06-07 19:56:00,0.0,NaN,Подарочный_сертификатна_Флайборд_(Выберите_тип...,4500.0,4500.0,4500,Флайборд_/_Ховерборд_/_Ранец,VMF306120784_13063,NaN,VKA4_3828822,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,VMF306120784,13063,MF306120784,electronic,design1,,0.0,,,,,NaT
2748,20910305,Успешно_реализовано,5000.0,2022-01-23 11:58:15,2022-01-23 11:58:00,NaN,NaN,NaN,NaN,NaN,5000,Моржевание+баня,KR1_17014148,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaT,NaN,,KR1,17014148,KR1,paper,design1,,0.0,,,,,NaT
3983,22125805,Успешно_реализовано,10900.0,2022-07-06 15:32:30,2022-07-07 19:51:00,NaN,NaN,Подарочный_сертификатна_вейкборд_(Выберите_тип...,10900.0,10900.0,10900,Вейксёрф_и_вейк_за_катером,TR2_15247945,NaN,WS60_210757,NaN,NaN,NaN,NaN,Погашен,2022-07-28,NaN,,TR2,15247945,TR2,paper,design1,sold_used,0.0,,,,,2022-07-28

In [185]:
dd0 = df_amo_temp.query('sale_price.isna()')

In [186]:
dd0.shape

(0, 35)

In [187]:
dd0.head()

Empty DataFrame
Columns: [amo_id, этап_сделки, бюджет, дата_создания_сделки, sale_date, delivery_price, стоимость_доставки, products, price, subtotal, выручка_от_клиента, направление_(вид_сертификата), code, корневая_сделка, номер_2-го_сертификата, номер_3-го_сертификата, номер_4-го_сертификата, номер_5-го_сертификата, сертификат_на_тренера, статус_погашения, card_used_date, стоимость_закупки, id, prefix, number, prefix_V, card_type, design_type, status, sale_price, expiry_date, created_at, updated_at, deleted_at, supplier_payment_date]
Index: []

Несколько записей так и не получили sale_price

In [188]:
df_amo_temp.info()

<class 'pandas.core.frame.DataFrame'>
Index: 9145 entries, 0 to 9175
Data columns (total 35 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   amo_id                         9145 non-null   int64
 1   этап_сделки                    8337 non-null   object
 2   бюджет                         8337 non-null   float64
 3   дата_создания_сделки           9145 non-null   datetime64[ns]
 4   sale_date                      9145 non-null   datetime64[ns]
 5   delivery_price                 5597 non-null   float64
 6   стоимость_доставки             500 non-null    object
 7   products                       7430 non-null   object
 8   price                          7430 non-null   float64
 9   subtotal                       8195 non-null   float64
 10  выручка_от_клиента             8134 non-null   object
 11  направление_(вид_сертификата)  9025 non-null   object
 12  code                           9145 non-null   object
 13  корневая_сделка                159 non-null    object
 14  номер_2-го_сертификата         712 non-null    object
 15  номер_3-го_сертификата         10 non-null     object
 16  номер_4-го_сертификата         4 non-null      object
 17  номер_5-го_сертификата         27 non-null     object
 18  сертификат_на_тренера          112 non-null    object
 19  статус_погашения               3284 non-null   object
 20  card_used_date                 3255 non-null   datetime64[ns]
 21  стоимость_закупки              2714 non-null   object
 22  id                             9145 non-null   object
 23  prefix                         9145 non-null   object
 24  number                         9145 non-null   object
 25  prefix_V                       9145 non-null   object
 26  card_type                      9145 non-null   object
 27  design_type                    9145 non-null   object
 28  status                         9145 non-null   object
 29  sale_price                     9145 non-null   float64
 30  expiry_date                    9145 non-null   object
 31  created_at                     9145 non-null   object
 32  updated_at                     9145 non-null   object
 33  deleted_at                     9145 non-null   object
 34  supplier_payment_date          3255 non-null   datetime64[ns]
dtypes: datetime64[ns](4), float64(5), int64(1), object(25)
memory usage: 2.5+ MB

### Проверка расчета sale_price для строк с дополнительными сертификатами

In [189]:
random_amoid_dopsert = dict()

Выбираем по 3  amo_id для каждого вида сертификата случайным образом

In [190]:
for k,v in dopsert_amoid.items():
#     print(k)
    if len(v)>=3:
        co = 3
    else:
        co = len(v)
    vv = random.sample(v, co)
    random_amoid_dopsert[k] = vv
pprint(random_amoid_dopsert)

{'номер_2-го_сертификата': [19381325, 21873761, 21931955],
 'номер_3-го_сертификата': [23717211, 26910087, 26946317],
 'номер_4-го_сертификата': [26910087, 24124551, 26906683],
 'номер_5-го_сертификата': [24901233, 9129063, 25538207],
 'сертификат_на_тренера': [24867945, 23869621, 24606011]}

In [191]:
for k,v in random_amoid_dopsert.items():
    df_temp = df_amo_temp.query('amo_id in @v')
    print('*'*80)
    print(k)
    print('-'*80)
    print(df_temp)

********************************************************************************
номер_2-го_сертификата
--------------------------------------------------------------------------------
        amo_id          этап_сделки  бюджет дата_создания_сделки  \
1959  19381325  Успешно_реализовано  3200.0  2021-07-21 11:19:49
3422  21873761  Успешно_реализовано  8700.0  2022-05-25 15:29:10
3530  21931955  Успешно_реализовано  5500.0  2022-06-05 12:15:35
8588  19381325                  NaN     NaN  2021-07-21 11:19:49
8733  21873761                  NaN     NaN  2022-05-25 15:29:10
8748  21931955                  NaN     NaN  2022-06-05 12:15:35

               sale_date  delivery_price стоимость_доставки  \
1959 2021-07-21 11:35:00             0.0                NaN
3422 2022-05-25 17:12:00             0.0                NaN
3530 2022-06-05 13:06:00             NaN                NaN
8588 2021-07-21 11:35:00             NaN                NaN
8733 2022-05-25 17:12:00             NaN                NaN
8748 2022-06-05 13:06:00             NaN                NaN

                                               products   price  subtotal  \
1959  Подарочный_сертификатна_сап-сёрфинг_(Выберите_...  3200.0    3200.0
3422  Подарочный_сертификатна_вейк_за_катером_(Выбер...  8700.0    8700.0
3530  Подарочный_сертификатна_вейксёрфинг_(Выберите_...  4500.0    4500.0
8588                                                NaN     NaN       0.0
8733                                                NaN     NaN       0.0
8748                                                NaN     NaN       0.0

     выручка_от_клиента направление_(вид_сертификата)            code  \
1959               3200                      САП-сёрф  VSU60_02254214
3422               8700    Вейксёрф_и_вейк_за_катером  VWS20_19562442
3530               4500    Вейксёрф_и_вейк_за_катером   WS30_15225476
8588                NaN                                  VSU60_022470
8733                NaN                                  VWS20_195250
8748                NaN                                    TR1_151996

     корневая_сделка номер_2-го_сертификата номер_3-го_сертификата  \
1959             NaN           VSU60_022470                    NaN
3422             NaN           VWS20_195250                    NaN
3530             NaN              TR1151996                    NaN
8588             NaN                    NaN                    NaN
8733             NaN                    NaN                    NaN
8748             NaN                    NaN                    NaN

     номер_4-го_сертификата номер_5-го_сертификата сертификат_на_тренера  \
1959                    NaN                    NaN                   NaN
3422                    NaN                    NaN                   NaN
3530                    NaN                    NaN                   NaN
8588                    NaN                    NaN                   NaN
8733                    NaN                    NaN                   NaN
8748                    NaN                    NaN                   NaN

     статус_погашения card_used_date стоимость_закупки id prefix    number  \
1959          Погашен     2021-10-12               NaN     VSU60  02254214
3422              NaN            NaT               NaN     VWS20  19562442
3530              NaN            NaT               NaN      WS30  15225476
8588              NaN            NaT               NaN     VSU60    022470
8733              NaN            NaT               NaN     VWS20    195250
8748              NaN            NaT               NaN       TR1    151996

     prefix_V   card_type design_type     status  sale_price expiry_date  \
1959     SU60  electronic     design1  sold_used      1600.0
3422     WS20  electronic     design1                 2600.0
3530     WS30       paper     design1                 3600.0
8588     SU60  electronic     design1                 1600.0
8733     WS20  electronic     design1                 2600.0
8748      TR1       paper     design1                    0.0

     created_at updated_at deleted_at supplier_payment_date
1959                                             2021-10-12
3422                                                    NaT
3530                                                    NaT
8588                                                    NaT
8733                                                    NaT
8748                                                    NaT
********************************************************************************
номер_3-го_сертификата
--------------------------------------------------------------------------------
        amo_id          этап_сделки   бюджет дата_создания_сделки  \
5249  23717211  Успешно_реализовано  23456.0  2023-02-21 11:37:56
8279  26910087  Успешно_реализовано  14600.0  2024-02-20 14:26:57
8339  26946317  Успешно_реализовано  19400.0  2024-02-23 08:57:18
8938  23717211                  NaN      NaN  2023-02-21 11:37:56
9021  26910087                  NaN      NaN  2024-02-20 14:26:57
9025  26946317                  NaN      NaN  2024-02-23 08:57:18
9028  23717211                  NaN      NaN  2023-02-21 11:37:56
9034  26910087                  NaN      NaN  2024-02-20 14:26:57
9035  26946317                  NaN      NaN  2024-02-23 08:57:18
9039  26910087                  NaN      NaN  2024-02-20 14:26:57

               sale_date  delivery_price стоимость_доставки  \
5249 2023-02-22 12:04:00             0.0                NaN
8279 2024-02-20 17:49:00           600.0                NaN
8339 2024-02-23 12:09:00             NaN                NaN
8938 2023-02-22 12:04:00             NaN                NaN
9021 2024-02-20 17:49:00             NaN                NaN
9025 2024-02-23 12:09:00             NaN                NaN
9028 2023-02-22 12:04:00             NaN                NaN
9034 2024-02-20 17:49:00             NaN                NaN
9035 2024-02-23 12:09:00             NaN                NaN
9039 2024-02-20 17:49:00             NaN                NaN

                                               products    price  subtotal  \
5249  Универсальный_23456_(Варианты:_23_456_руб.,_Бу...  23456.0   23456.0
8279  Полёт_на_авиатренажёре_(Варианты:_30_минут_пол...  14600.0   14000.0
8339  Гидрофойл_(Варианты:_Курс_25_минут_-_Mastercra...  19400.0   19400.0
8938                                                NaN      NaN       0.0
9021                                                NaN      NaN       0.0
9025                                                NaN      NaN       0.0
9028                                                NaN      NaN       0.0
9034                                                NaN      NaN       0.0
9035                                                NaN      NaN       0.0
9039                                                NaN      NaN       0.0

     выручка_от_клиента направление_(вид_сертификата)             code  \
5249              23456      Универс._23.456_и_34.567    WTF2_15049455
8279              14600             Авиа_Авиатренажер    AC30_25144006
8339              19400            Вейксёрф_Гидрофоил  VHY30_701681282
8938                NaN                                   VGU2_8015335
9021                NaN                                     AC30_25911
9025                NaN                                  VWS25_9016165
9028                NaN                                   VGU2_9015347
9034                NaN                                     AC30_25815
9035                NaN                                  VMF20_2016187
9039                NaN                                     AC30_25743

     корневая_сделка номер_2-го_сертификата номер_3-го_сертификата  \
5249             NaN           VGU2_8015335           VGU2_9015347
8279             NaN             AC30_25911             AC30_25815
8339             NaN          VWS25_9016165          VMF20_2016187
8938             NaN                    NaN                    NaN
9021             NaN                    NaN                    NaN
9025             NaN                    NaN                    NaN
9028             NaN                    NaN                    NaN
9034             NaN                    NaN                    NaN
9035             NaN                    NaN                    NaN
9039             NaN                    NaN                    NaN

     номер_4-го_сертификата номер_5-го_сертификата сертификат_на_тренера  \
5249                    NaN                    NaN                   NaN
8279             AC30_25743                    NaN                   NaN
8339                    NaN                    NaN                   NaN
8938                    NaN                    NaN                   NaN
9021                    NaN                    NaN                   NaN
9025                    NaN                    NaN                   NaN
9028                    NaN                    NaN                   NaN
9034                    NaN                    NaN                   NaN
9035                    NaN                    NaN                   NaN
9039                    NaN                    NaN                   NaN

     статус_погашения card_used_date стоимость_закупки id prefix     number  \
5249          Погашен     2024-02-18             18765      WTF2   15049455
8279              NaN            NaT              2800      AC30   25144006
8339              NaN            NaT               NaN     VHY30  701681282
8938              NaN            NaT               NaN      VGU2    8015335
9021              NaN            NaT               NaN      AC30      25911
9025              NaN            NaT               NaN     VWS25    9016165
9028              NaN            NaT               NaN      VGU2    9015347
9034              NaN            NaT               NaN      AC30      25815
9035              NaN            NaT               NaN     VMF20    2016187
9039              NaN            NaT               NaN      AC30      25743

     prefix_V   card_type design_type     status  sale_price expiry_date  \
5249     WTF2       paper     design1  sold_used     23456.0
8279     AC30       paper     design1                 3500.0
8339     HY30  electronic     design1                 4500.0
8938      GU2  electronic     design1                 9500.0
9021     AC30       paper     design1                 3500.0
9025     WS25  electronic     design1                 6700.0
9028      GU2  electronic     design1                 9500.0
9034     AC30       paper     design1                 3500.0
9035     MF20  electronic     design1                 2600.0
9039     AC30       paper     design1                 3500.0

     created_at updated_at deleted_at supplier_payment_date
5249                                             2024-02-18
8279                                                    NaT
8339                                                    NaT
8938                                                    NaT
9021                                                    NaT
9025                                                    NaT
9028                                                    NaT
9034                                                    NaT
9035                                                    NaT
9039                                                    NaT
********************************************************************************
номер_4-го_сертификата
--------------------------------------------------------------------------------
        amo_id          этап_сделки   бюджет дата_создания_сделки  \
5628  24124551  Успешно_реализовано  15600.0  2023-04-20 19:16:41
8272  26906683  Успешно_реализовано  12000.0  2024-02-20 10:40:01
8279  26910087  Успешно_реализовано  14600.0  2024-02-20 14:26:57
8942  24124551                  NaN      NaN  2023-04-20 19:16:41
9019  26906683                  NaN      NaN  2024-02-20 10:40:01
9021  26910087                  NaN      NaN  2024-02-20 14:26:57
9029  24124551                  NaN      NaN  2023-04-20 19:16:41
9033  26906683                  NaN      NaN  2024-02-20 10:40:01
9034  26910087                  NaN      NaN  2024-02-20 14:26:57
9037  24124551                  NaN      NaN  2023-04-20 19:16:41
9038  26906683                  NaN      NaN  2024-02-20 10:40:01
9039  26910087                  NaN      NaN  2024-02-20 14:26:57
9050  24124551                  NaN      NaN  2023-04-20 19:16:41
9110  24124551                  NaN      NaN  2023-04-20 19:16:41

               sale_date  delivery_price стоимость_доставки  \
5628 2023-04-20 20:30:00             0.0                NaN
8272 2024-02-23 16:29:00             NaN                NaN
8279 2024-02-20 17:49:00           600.0                NaN
8942 2023-04-20 20:30:00             NaN                NaN
9019 2024-02-23 16:29:00             NaN                NaN
9021 2024-02-20 17:49:00             NaN                NaN
9029 2023-04-20 20:30:00             NaN                NaN
9033 2024-02-23 16:29:00             NaN                NaN
9034 2024-02-20 17:49:00             NaN                NaN
9037 2023-04-20 20:30:00             NaN                NaN
9038 2024-02-23 16:29:00             NaN                NaN
9039 2024-02-20 17:49:00             NaN                NaN
9050 2023-04-20 20:30:00             NaN                NaN
9110 2023-04-20 20:30:00             NaN                NaN

                                               products    price  subtotal  \
5628  катание_на_картинге_(Варианты:_20_минут_катани...  15600.0   15600.0
8272  катание_на_картинге_(Варианты:_20_минут_катани...  12000.0   12000.0
8279  Полёт_на_авиатренажёре_(Варианты:_30_минут_пол...  14600.0   14000.0
8942                                                NaN      NaN       0.0
9019                                                NaN      NaN       0.0
9021                                                NaN      NaN       0.0
9029                                                NaN      NaN       0.0
9033                                                NaN      NaN       0.0
9034                                                NaN      NaN       0.0
9037                                                NaN      NaN       0.0
9038                                                NaN      NaN       0.0
9039                                                NaN      NaN       0.0
9050                                                NaN      NaN       0.0
9110                                                NaN      NaN       0.0

     выручка_от_клиента направление_(вид_сертификата)            code  \
5628              15600                       Картинг  VKA2_281938230
8272              12000                       Картинг   KA2_000893320
8279              14600             Авиа_Авиатренажер   AC30_25144006
8942                NaN                                  VKA2_2919588
9019                NaN                                   KA2_9008064
9021                NaN                                    AC30_25911
9029                NaN                                  VKA2_2919594
9033                NaN                                   KA2_2008078
9034                NaN                                    AC30_25815
9037                NaN                                  VKA2_2919609
9038                NaN                                   KA2_3008097
9039                NaN                                    AC30_25743
9050                NaN                                  VKA2_2919610
9110                NaN                                  VKA2_2919620

     корневая_сделка номер_2-го_сертификата номер_3-го_сертификата  \
5628             NaN           VKA2_2919588           VKA2_2919594
8272             NaN            KA2_9008064            KA2_2008078
8279             NaN             AC30_25911             AC30_25815
8942             NaN                    NaN                    NaN
9019             NaN                    NaN                    NaN
9021             NaN                    NaN                    NaN
9029             NaN                    NaN                    NaN
9033             NaN                    NaN                    NaN
9034             NaN                    NaN                    NaN
9037             NaN                    NaN                    NaN
9038             NaN                    NaN                    NaN
9039             NaN                    NaN                    NaN
9050             NaN                    NaN                    NaN
9110             NaN                    NaN                    NaN

     номер_4-го_сертификата номер_5-го_сертификата сертификат_на_тренера  \
5628           VKA2_2919609           VKA2_2919610          VKA2_2919620
8272            KA2_3008097                    NaN                   NaN
8279             AC30_25743                    NaN                   NaN
8942                    NaN                    NaN                   NaN
9019                    NaN                    NaN                   NaN
9021                    NaN                    NaN                   NaN
9029                    NaN                    NaN                   NaN
9033                    NaN                    NaN                   NaN
9034                    NaN                    NaN                   NaN
9037                    NaN                    NaN                   NaN
9038                    NaN                    NaN                   NaN
9039                    NaN                    NaN                   NaN
9050                    NaN                    NaN                   NaN
9110                    NaN                    NaN                   NaN

     статус_погашения card_used_date стоимость_закупки id prefix     number  \
5628          Погашен     2023-06-09             13200      VKA2  281938230
8272              NaN            NaT              2200       KA2  000893320
8279              NaN            NaT              2800      AC30   25144006
8942              NaN            NaT               NaN      VKA2    2919588
9019              NaN            NaT               NaN       KA2    9008064
9021              NaN            NaT               NaN      AC30      25911
9029              NaN            NaT               NaN      VKA2    2919594
9033              NaN            NaT               NaN       KA2    2008078
9034              NaN            NaT               NaN      AC30      25815
9037              NaN            NaT               NaN      VKA2    2919609
9038              NaN            NaT               NaN       KA2    3008097
9039              NaN            NaT               NaN      AC30      25743
9050              NaN            NaT               NaN      VKA2    2919610
9110              NaN            NaT               NaN      VKA2    2919620

     prefix_V   card_type design_type     status  sale_price expiry_date  \
5628      KA2  electronic     design1  sold_used      2600.0
8272      KA2       paper     design1                 2600.0
8279     AC30       paper     design1                 3500.0
8942      KA2  electronic     design1                 2600.0
9019      KA2       paper     design1                 2600.0
9021     AC30       paper     design1                 3500.0
9029      KA2  electronic     design1                 2600.0
9033      KA2       paper     design1                 2600.0
9034     AC30       paper     design1                 3500.0
9037      KA2  electronic     design1                 2600.0
9038      KA2       paper     design1                 2600.0
9039     AC30       paper     design1                 3500.0
9050      KA2  electronic     design1                 2600.0
9110      KA2  electronic     design1                 2600.0

     created_at updated_at deleted_at supplier_payment_date
5628                                             2023-06-09

## Запись в файлы

### Объединение датафреймов без префиксов и с отсутствующими в базах префиксами и запись в файл

In [192]:
df_amo_missing_prefix = df_amo_temp.query('prefix in @missing_prefix')

In [193]:
df_amo_missing_prefix.shape

(16, 35)

In [194]:
frames = [df_amo_without_prefix, df_amo_missing_prefix]

In [195]:
cert_w_missing_prefix = pd.concat(frames)

In [196]:
cert_w_missing_prefix.shape

(47, 35)

In [197]:
cert_w_missing_prefix.to_csv('r_cert_w_missing_prefix' + date_int + '.csv')

### Запись отсутствующих в Списке подкатегорий prefix в файл

In [198]:
df_missing_prefix = pd.DataFrame({'prefix':missing_prefix})

In [199]:
df_missing_prefix.shape

(38, 1)

In [200]:
df_missing_prefix.head()

   prefix
0
1  60WAKE
2      AT
3     AWP
4       D

In [201]:
df_missing_prefix.to_csv('r_missing_prefix' + date_int + '.csv')

### (п.10) Запись товаров, необходимые поля которого заполнены

In [202]:
df_amo_temp['amo_lead_id'] = df_amo_temp['amo_id']

In [203]:
df_amo_temp['amo_id'] = ''

Итоговые столбцы из АМО

In [204]:
lst_afm = ['id', 
           'amo_id',
           'amo_lead_id',
           'prefix',
           'prefix_V',
           'code',
           'card_type',
           'design_type',
           'status',
           'supplier_payment_date',
           'sale_price',
           'sale_date',
           'expiry_date',
           'card_used_date',
           'created_at',
           'updated_at',
           'deleted_at',
           'number',
]

Итоговые столбцы из Реестра

In [205]:
df_values['prefix_V'] = df_values['prefix']

In [206]:
lst_val = ['activity_value_id','prefix_V']

Датафреймы для объединения

In [207]:
df_amo_for_merge = df_amo_temp.query('prefix_V in @prefix_values')

In [208]:
df_amo_for_merge = df_amo_for_merge[lst_afm]

In [209]:
df_amo_for_merge.head()

,id,amo_id,amo_lead_id,prefix,prefix_V,code,card_type,design_type,status,supplier_payment_date,sale_price,sale_date,expiry_date,card_used_date,created_at,updated_at,deleted_at,number
0,,,660235,KVP1X1,KVP1X1,KVP1X1_01053659,paper,design1,,NaT,3000.0,2020-07-10 10:39:00,,NaT,,,,01053659
1,,,667573,MF20,MF20,MF20_95425,paper,design1,sold_used,2020-07-01,2600.0,2020-07-10 10:40:00,,2020-07-01,,,,95425
4,,,938619,KVP2X1,KVP2X1,KVP2X1_01053332,paper,design1,,NaT,6000.0,2020-03-08 05:06:00,,NaT,,,,01053332
5,,,948101,SU24,SU24,SU24_43411,paper,design1,sold_used,2020-08-09,5000.0,2020-07-10 18:34:00,,2020-08-09,,,,43411
7,,,1418327,VKV1X1,KV1X1,VKV1X1_02095845,electronic,design1,,NaT,3000.0,2020-07-10 18:34:00,,NaT,,,,02095845

In [210]:
df_value_for_merge = df_values[lst_val]

Объединение датафреймов

In [211]:
df_list = pd.merge(df_amo_for_merge, df_value_for_merge,how="inner",on='prefix_V')

In [212]:
df_list.head()

,id,amo_id,amo_lead_id,prefix,prefix_V,code,card_type,design_type,status,supplier_payment_date,sale_price,sale_date,expiry_date,card_used_date,created_at,updated_at,deleted_at,number,activity_value_id
0,,,660235,KVP1X1,KVP1X1,KVP1X1_01053659,paper,design1,,NaT,3000.0,2020-07-10 10:39:00,,NaT,,,,01053659,122
1,,,1447181,KVP1X1,KVP1X1,KVP1X1_01053485,paper,design1,,NaT,4000.0,2020-07-10 18:34:00,,NaT,,,,01053485,122
2,,,2043495,KVP1X1,KVP1X1,KVP1X1_01194114,paper,design1,,NaT,3000.0,2020-03-12 16:46:00,,NaT,,,,01194114,122
3,,,3448569,KVP1X1,KVP1X1,KVP1X1_01065471,paper,design1,,NaT,3000.0,2020-07-10 18:31:00,,NaT,,,,01065471,122
4,,,3448563,KVP1X1,KVP1X1,KVP1X1_01042676,paper,design1,,NaT,3000.0,2020-07-10 18:31:00,,NaT,,,,01042676,122

In [213]:
df_list = df_list.drop('prefix_V', axis=1)

In [214]:
df_list.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6755 entries, 0 to 6754
Data columns (total 18 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     6755 non-null   object
 1   amo_id                 6755 non-null   object
 2   amo_lead_id            6755 non-null   int64
 3   prefix                 6755 non-null   object
 4   code                   6755 non-null   object
 5   card_type              6755 non-null   object
 6   design_type            6755 non-null   object
 7   status                 6755 non-null   object
 8   supplier_payment_date  2379 non-null   datetime64[ns]
 9   sale_price             6755 non-null   float64
 10  sale_date              6755 non-null   datetime64[ns]
 11  expiry_date            6755 non-null   object
 12  card_used_date         2379 non-null   datetime64[ns]
 13  created_at             6755 non-null   object
 14  updated_at             6755 non-null   object
 15  deleted_at             6755 non-null   object
 16  number                 6755 non-null   object
 17  activity_value_id      6755 non-null   int64
dtypes: datetime64[ns](3), float64(1), int64(2), object(12)
memory usage: 950.1+ KB

Запись в файл

In [215]:
df_list.to_csv('r_certs_to_import' + date_int +'.csv')

### (п.11) Список товаров, чьи префиксы не обнаружены в list_of_values.csv, но есть в codes_archieve

In [216]:
df_amo_temp = df_amo_temp.query('prefix_V in @archive_prefix')

In [217]:
df_amo_for_write = df_amo_temp[lst_afm]

In [218]:
df_amo_for_write = df_amo_for_write.drop('prefix_V', axis=1)

In [219]:
df_amo_for_write.head()

,id,amo_id,amo_lead_id,prefix,code,card_type,design_type,status,supplier_payment_date,sale_price,sale_date,expiry_date,card_used_date,created_at,updated_at,deleted_at,number
3,,,929931,VWS60,VWS60_22477,electronic,design1,,NaT,7500.0,2020-07-10 18:34:00,,NaT,,,,22477
19,,,2043467,GR1X1,GR1X1_01015399,paper,design1,sold_used,NaT,2750.0,2020-07-10 18:34:00,,NaT,,,,01015399
31,,,3448575,WS60,WS60_79578,paper,design1,,NaT,7500.0,2020-07-10 18:31:00,,NaT,,,,79578
34,,,3448561,GR1X1,GR1X1_01082291,paper,design1,,NaT,2750.0,2020-07-10 18:31:00,,NaT,,,,01082291
45,,,4332787,VGR1X1,VGR1X1_01067683,electronic,design1,,NaT,2750.0,2020-07-10 18:31:00,,NaT,,,,01067683

In [220]:
df_amo_for_write.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1994 entries, 3 to 9175
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   id                     1994 non-null   object
 1   amo_id                 1994 non-null   object
 2   amo_lead_id            1994 non-null   int64
 3   prefix                 1994 non-null   object
 4   code                   1994 non-null   object
 5   card_type              1994 non-null   object
 6   design_type            1994 non-null   object
 7   status                 1994 non-null   object
 8   supplier_payment_date  694 non-null    datetime64[ns]
 9   sale_price             1994 non-null   float64
 10  sale_date              1994 non-null   datetime64[ns]
 11  expiry_date            1994 non-null   object
 12  card_used_date         694 non-null    datetime64[ns]
 13  created_at             1994 non-null   object
 14  updated_at             1994 non-null   object
 15  deleted_at             1994 non-null   object
 16  number                 1994 non-null   object
dtypes: datetime64[ns](3), float64(1), int64(1), object(12)
memory usage: 280.4+ KB

In [221]:
df_amo_for_write.to_csv('r_certs_to_import_archieve_prefix' + date_int +'.csv')